### ISSUE TITLE
No DisplayLayout template "GRAPHIC_WITH_TEXT"

### ISSUE THREAD

**Issue by BrandonHe** [smartdevicelink/sdl_hmi#10]
When app needs to SetDisplayLayout with template "GRAPHIC_WITH_TEXT", connected and tested with sdl_core and sdl_hmi, it response "UNSUPPORTED_REQUEST".
We searched in this repo, seems here only one template in [UI.GetCapabilities](https://github.com/smartdevicelink/sdl_hmi/blob/6699ec950660d81af30bb7ba73b167da23967152/ffw/UIRPC.js#L920) that hmi can response for app request, whatever [hmi_capabilities](https://github.com/smartdevicelink/sdl_core/blob/master/src/appMain/hmi_capabilities.json) template supported in sdl_core side. Actually, totally 15 [standard templates](https://www.smartdevicelink.com/en/guides/iOS/getting-started/designing-the-user-interface/) should be supported in hmi.

**Comment by tpulatha** [comment]
sdl_hmi does not support different layouts at this time. We are working on a replacement. In the meantime you can use the Ford specific emulator @ developer.ford.com

**Comment by BrandonHe** [comment]
@tpulatha Thanks!
I have successfully set up our Ford SYNC3 emulator, but here we are developing a new [HMI](https://github.com/APCVSRepo/hmi_sdk) that needs to support different layouts, we don't know how to support these templates.

**Comment by jacobkeeler** [comment]
SDL HMI does not support this template at this time and the capabilities have been changed to reflect this
