### ISSUE TITLE
HMI does not show RC apps from second device

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#112]
Steps to reproduce:
1. Connect device_1
2. Register RC app_1 from device_1
3. Connect device_2
4. Register RC app_2 from device_2

Expected result: all apps are registered and shown on HMI.
Actual result: App_2 from device_2 is registered, but is not shown on HMI.

**Comment by GetmanetsIrina** [comment]
Fix for issue is in https://github.com/smartdevicelink/sdl_hmi/pull/111

**Comment by iCollin** [comment]
Closed as not reproducible
