### ISSUE TITLE
SDL HMI does not support remote control SEAT by default

### ISSUE THREAD

**Issue by yang1070** [smartdevicelink/sdl_hmi#143]
### Bug Report
HMI does not support remote control SEAT in capability

##### Reproduction Steps
1. register and activate a remote control app
2. send a valid GetInteriorVehilceData request regarding SEAT moduleType

##### Expected Behavior

App get SEAT module data

##### Observed Behavior
app get UNSUPPORTED_RESOURCE error.
Also there is no seat related capability in the GetSystemCapability response

##### OS & Version Information
- OS/Version: Ubuntu 16.04
- SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/5.0.0_RC2
- test remote control regarding SEAT

**Comment by GetmanetsIrina** [comment]
issue duplicates https://github.com/smartdevicelink/sdl_hmi/issues/141

**Comment by yang1070** [comment]
same root cause as https://github.com/smartdevicelink/sdl_hmi/issues/142
