### ISSUE TITLE
HMI does not send heatingLevel in OnInteriorVehicleData after update from HMI

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#145]
### Bug Report
HMI does not send heatingLevel in OnInteriorVehicleData after update from HMI

##### Occurrences
Once

##### Reproduction Steps
1. RC app is registered and activated
2. App is subscribed to SEAT module
3. Update heating level on HMI and press Set button

##### Expected Behavior
HMI sends OnInteriorVehicleData notification with heatingLevel with updated value and SDL transfer notification to mobile app

##### Observed Behavior
HMI does not send heatingLevel in OnInteriorVehicleData after update

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/c9697970a6ad6300936fe893efe7f3acae92a7c0
* Testing Against: HMI version: https://github.com/smartdevicelink/sdl_hmi/commit/35e5c1a38b8e3856c90456346f2703e00cca7d64, SPT: 4.6.3

**Comment by Ypostolov** [comment]
@GetmanetsIrina 
Defect is not reproducible.
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (5646341)
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (c813503)
Please confirm.

**Comment by GetmanetsIrina** [comment]
Confirmed on 
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (d50140f)
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (6560d02)
