### ISSUE TITLE
HMI does not update values  in drop-down on SEAT form in case values are updated via SetInteriorVD

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#146]
### Bug Report
HMI does not update values in drop-down list on SEAT form in case values are updated via SetInteriorVD 

##### Occurrences
Sometimes

##### Reproduction Steps
1. RC app is registered and activated
2. Go to SEAT form and change id to DRIVER
3. App requests SetInteriorVD with updated parameters for DRIVER id and for parameters in drop-down list

##### Expected Behavior
HMI must update values on SEAT form according to changes in SetInteriorVD requets

##### Observed Behavior
HMI does not update values on SEAT form, but sends actual values in OnInteriorVD and in SetInteriorVD response

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/c9697970a6ad6300936fe893efe7f3acae92a7c0
* Testing Against: HMI version: https://github.com/smartdevicelink/sdl_hmi/commit/35e5c1a38b8e3856c90456346f2703e00cca7d64, SPT: 4.6.3

**Comment by VjKlepikov** [comment]
Issue is not reproducible
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop [(29a052c5)](https://github.com/smartdevicelink/sdl_hmi/commit/29a052c525d101cc60914e0e2edf86720d128c4c)
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop [cb42c62](https://github.com/smartdevicelink/sdl_core/commit/cb42c627b837df0ce184ba849c232dd36bd92c91)
