### ISSUE TITLE
HMI does not remove the group entries in app permissions list

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#148]
Precondition: SDL must be built with EXTERNAL_PROPRIETARY flag

Steps to reproduce:
1. Register app
2. Perform PTU with groups that needs the user consent( after app registration and activation send SystemRequest(PROPRIETARY) with required file for update )
3. After PTU there are 2 entries in app permissions list
4. Perform update without groups for user consent( Trigger the ptu from HMI vie UpdateSDL in Settings and send SystemRequest(PROPRIETARY) with required file for update )
5. Go to app permissions list

Expected result: The list of app permissions for defined app is empty

Actual result: The list contains 2 records from previous update and they can be pressed and HMI sends some invalid message `{"jsonrpc":"2.0","method":"SDL.OnAppPermissionConsent","params":{"source":"GUI","consentedFunctions":[{"allowed":true},{}],"appID":0}}` 

SDL branch: https://github.com/smartdevicelink/sdl_core/commit/17c3f5114533f954d9afea8166c1d3d7b3adff2a
Mobile app version: 4.6.3 20180912
OS version: Ubuntu 16.04
Files for update: 
[files_for_ptu.tar.gz](https://github.com/smartdevicelink/sdl_hmi/files/2484585/files_for_ptu.tar.gz)

**Comment by jacobkeeler** [comment]
Closing with the merge of #424

**Comment by GetmanetsIrina** [comment]
Sending of invalid OnAppPermissionConsent notification is not fixed.
New issue has been created https://github.com/smartdevicelink/sdl_hmi/issues/446 .
