### ISSUE TITLE
mb_tcpserver.cpp:96 Received 4096 actual data length 4916

### ISSUE THREAD

**Issue by cat-fang** [smartdevicelink/sdl_hmi#167]
When I connect android phone with sdl core, the error occurred while playing music from the phone apk. The errors are follow:

ERROR!!! /usr/src/debug/sdl-core/4.4.1-r0/git/src/3rd_party-static/message_broker/src/server/mb_tcpserver.cpp:96 Received 4096 actual data length 4916
ERROR!!! /usr/src/debug/sdl-core/4.4.1-r0/git/src/3rd_party-static/message_broker/src/server/mb_tcpserver.cpp:97 Incomplete messageERROR!!! 

How to solve the problem?
The sdl-core was runned on AGL platform.
sdl core version is : 4.4.0

Thanks

**Comment by jacobkeeler** [comment]
This is a false alarm message that was present in older versions of Core, it can be safely ignored
