### ISSUE TITLE
HMI sends OnDriverDistraction notification to SDL twice

### ISSUE THREAD

**Issue by ONyzhnyk-Luxoft** [smartdevicelink/sdl_hmi#172]
Preconditions:

1) Start SDL and HMI
2) Connect mobile device via any transport
3) Register app and activate app

Steps to reproduce:

1) Check the “DD” box
2) Uncheck “DD”

Actual result:

HMI sends an OnDriverDistraction notification to the SDL twice, and the mobile application receives two notifications

 *- HMI→SDL: "OnDriverDistraction"( "DD_ON" )*
 - *HMI→SDL: "OnDriverDistraction"( "DD_ON" )*

 - SDL→*MOB: "OnDriverDistraction"( "DD_ON")*
 - SDL→MOB: "OnDriverDistraction"( "DD_ON")

 - HMI→SDL: "OnDriverDistraction"( "DD_OFF" )
 - HMI→SDL: "OnDriverDistraction"( "DD_OFF" )

 - SDL→MOB: "OnDriverDistraction"( "DD_OFF")
 - SDL→MOB: "OnDriverDistraction"( "DD_OFF")

Expected result:

HMI sends one OnDriverDistraction notification to the SDL, and the mobile application receives one notification:

 *- HMI→SDL: "OnDriverDistraction"( "DD_ON" )*
 - SDL→MOB: "OnDriverDistraction"( "DD_ON")

  - HMI→SDL: "OnDriverDistraction"( "DD_OFF" )
 - SDL→MOB: "OnDriverDistraction"( "DD_OFF")

**Comment by KhrystynaDubovyk** [comment]
@theresalech, please triage this issue. We assume this is not a regression issue.
Also, please see the fix provided by Luxoft team.

**Comment by iCollin** [comment]
Closed via #192
