### ISSUE TITLE
AlertManeuver pop-up with softButtons is not shown on HMI

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#174]
### Bug Report
AlertManeuver pop-up with softButtons is not shown on HMI

##### Reproduction Steps
1. HMI and SDL are started
2. Mobile app is registered and activated
3. Request AlertManeuver with softButtons

##### Expected Behavior
HMI shows AlertManeuver pop-up with softButtons

##### Observed Behavior
HMI does not show AlertManeuver pop-up with softButtons and sends response right after request is received.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: 5.0.1
* Testing Against: HMI 5.0.1

**Comment by jacobkeeler** [comment]
For now perhaps `UNSUPPORTED_REQUEST` should be returned?
