### ISSUE TITLE
HMI responds 'REJECTED' to a request from SDL on RC.ButtonPress from the App2

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_hmi#179]
### Bug Report
HMI responds 'REJECTED' to a request from SDL on RC.ButtonPress from the App2

##### Precondotions
1) In sdl_preloaded_pt.json default app_policies groups: ["Base-4", "RemoteControl"], moduleType: ["RADIO", "CLIMATE"] HMI support new RC module
2) Start SDL and HMI
3) Connect mobile devices via any transport
4) Running the same application on the different devices with Remote_Control HMI type

##### Steps
1) App1 is activated and allocates module_RADIO via ButtonPress
2) App2 is activated and tries to allocate module_CLIMATE via ButtonPress

##### Expected Behavior
HMI must update values on SEAT form according to changes in SetInteriorVD requets

##### Actual result:
HMI responds 'REJECTED' to a request from SDL on RC.ButtonPress from the App2

##### Expected result:
HMI responds 'SUCCESS' to a request from SDL on RC.ButtonPress from the App2

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [same_app_from_multiple_devices](https://github.com/smartdevicelink/sdl_core/tree/develop) (  708b042  )
* HMI version: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop) (78b2d45 )
SPT: 20190122 Nightly-Android

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/191
