### ISSUE TITLE
Resumption.Application data is not restored on HMI after unexpected disconnect and connect are performed

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_hmi#180]
### Bug Report
Resumption.Application data is not restored on HMI after unexpected disconnect and connect are performed

##### Steps
1.SDL and HMI are started
2. App1is registered
3. App1 added AddCommand
4. Unexpected disconnect and connect are performed

##### Expected Behavior
SDL sends data for resuming after sending "BasicCommunication.OnAppRegistered" to the HMI

##### Actual result:
SDL sends data for resuming before sending "BasicCommunication.OnAppRegistered" to the HMI and On HMI does not display all data for applications

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [same_app_from_multiple_devices](https://github.com/smartdevicelink/sdl_core/tree/develop) (  708b042  )
* HMI version: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop) (78b2d45 )
SPT: 20190122 Nightly-Android

##### Attachments
[sdl.log.and.hmi.log.zip](https://github.com/smartdevicelink/sdl_hmi/files/3103696/sdl.log.and.hmi.log.zip)

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/191
