### ISSUE TITLE
On HMI not displayed the second App

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_hmi#181]
### Bug Report
On HMI not displayed the second App

##### Steps
1) SDL and HMI are started
2) Connect mobile devices via any transport
3) App1 and App2 are registered with Remote_Control HMI type

##### Expected Behavior
HMI must update values on SEAT form according to changes in SetInteriorVD requets

##### Actual result:
On HMI displayed only one app of two

##### Expected result:
On HMI displayed both apps

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [same_app_from_multiple_devices](https://github.com/smartdevicelink/sdl_core/tree/develop) (  708b042  )
* HMI version: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop) (78b2d45 )
SPT: 20190122 Nightly-Android

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/191
