### ISSUE TITLE
Selecting a choice set item from the VR menu always fails

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_hmi#214]
### Bug Report
Selecting a voice-recognition choice set item from the sdl_hmi's VR menu does nothing. Eventually, the perform interaction times out and a `PerformInteraction` response with an error is returned.

##### Reproduction Steps
1. Connect SDL_iOS example app to sdl_core and sdl_hmi
2. Open the VR menu in sdl_hmi and select **Perform Interaction Choice Set Menu Example**. This will trigger sending a `PerformInteraction` request with an `interactionMode` of `VR_ONLY`. The choice set items show up in the VR menu. 
3. Select a choice set item from the VR menu.

##### Expected Behavior
A `PerformInteraction` with information about the selected choice set item is returned.

##### Observed Behavior
Nothing happens. Eventually, the perform interaction times out and a `PerformInteraction` response with an error is returned.

##### OS & Version Information
* sdl_hmi version: 5.1.0
* sdl_core version: 5.1.3
* Testing with: SDL_iOS example app (v. 6.3)

**Comment by theresalech** [comment]
Closed via #224
