### ISSUE TITLE
BasicCommunication.onReady notification send two times instead of one time from the web hmi

### ISSUE THREAD

**Issue by ghost** [smartdevicelink/sdl_hmi#218]
### Bug Report
The `BasicCommunication.onReady` notification send two times instead of one time from the web hmi. 

##### Reproduction Steps
1. Start SDL and HMI
2. Check the console output of the Web HMI.

##### Expected Behavior
`BasicCommunication.onReady` notification sends one time

##### Observed Behavior
`BasicCommunication.onReady` notification sends two times

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: 30922d5884f2388b33537fd6e40f5cad27f6478d
* sdl_core branch: [develop](https://github.com/smartdevicelink/sdl_core/commits/develop)

**Comment by ValeriiMalkov** [comment]
Fixed in PR [#219](https://github.com/smartdevicelink/sdl_hmi/pull/219)

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/400
