### ISSUE TITLE
An alert ignores the set `duration` if a soft button is added to the alert

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_hmi#226]
# Bug Report
An alert ignores the set `duration` if a soft button is added to the alert. The alert eventually times out after showing for a minute with an `ABORTED` `resultCode`. 

If this is indeed the correct behavior, the RPC spec should be updated to note that the timeout will be ignored if a soft button is added to the `Alert`.

##### Reproduction Steps
1. Create an `Alert` RPC with the `duration` set to `5000` and at least one soft button in the `softButtons` array.
    ```
    Send RPC Alert (request), id: 76
    {
        alertText1 = "This app does not have the required permissions to access vehicle data";
        duration = 5000;
        playTone = 0;
        progressIndicator = 0;
        softButtons =     (
            "{\n    isHighlighted = 1;\n    softButtonID = 1;\n    text = OK;\n    type = TEXT;\n}"
        );
    }
    ```
2. Wait for the timeout to occur.

##### Expected Behavior
The alert should dismiss after 5 seconds.

##### Observed Behavior
The alert dismisses after 1 minute.

##### OS & Version Information
* sdl_hmi version: 5.1.0
* sdl_core version: 5.1.3
* Testing with: SDL_iOS Swift example app (v. 6.3.1)

**Comment by jacobkeeler** [comment]
This is definitely an intended behavior, based on the Core code: https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/alert_request.cc#L82-L89

This is documented in the HMI integration guidelines as well: https://smartdevicelink.com/en/guides/hmi/ui/alert/#alert

This issue can be moved to the RPC spec repo, since it would need to be documented there

**Comment by NicoleYarroch** [comment]
@jacobkeeler Can you [transfer](https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository) this issue to the rpc_spec repo? I don't have write permissions on this repo.

**Comment by jacobkeeler** [comment]
@NicoleYarroch already created a new issue: https://github.com/smartdevicelink/rpc_spec/issues/235

I'll keep the transfer option in mind for next time though
