### ISSUE TITLE
Images Supported Only Returns Static

### ISSUE THREAD

**Issue by justingluck93** [smartdevicelink/sdl_hmi#236]
The `ImagesSupported` array is only showing static but `Dynamic` should also be supported.

## Reproduction Steps
Connect to SDL_HMI Develop and check the the SDLWindowCapability response.

## Expected Behavior
Array to include Dynamic

## Observed Behavior
Array does not include Dynamic

```
imageTypeSupported =     (
        STATIC
    );
```

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/242
