### ISSUE TITLE
SetMediaClockTimer: progress-bar does not displayed and The counter continues to count the time from set endTime on HMI

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_hmi#238]
**Preconditions**:
1) SDL and HMI are started
2) Media app is registered and activated on HMI

**Step**:
1) App sends SetMediaClockTimer
- Enable `Start Time`( Enter 0 for all fields )
- Enable `End Time` ( Enter 0 for hours, 0 for minutes, and 30 for seconds )
- Make sure `Update Mode` is set to `COUNTUP`

*Expected result: *
A timer should pop up counting up from 00:00:00 to 00:00:30, with a bar showing the progress of the count

**Actual result:**
- A timer displayed.
- The counter continues to count the time(goes beyond 30 sec and do not stop).
- A bar does not displayed and does not showing the progress of the count

**Attachment**:
[SetMediaClockTimer_RPC.tar.gz](https://github.com/smartdevicelink/sdl_hmi/files/3707994/SetMediaClockTimer_RPC.tar.gz)

**Comment by AKalinich-Luxoft** [comment]
Luxoft team is preparing a fix

**Comment by AKalinich-Luxoft** [comment]
@HSavynetska looks like this issue is not actual as [[SDL 0084] Progress Bar Seek Feature](https://github.com/smartdevicelink/sdl_hmi/pull/166) is not included into release 6.0
Functionality descibed in this pull request was implemented in this proposal. For a current develop this test case is not applicable.

**Comment by jordynmackool** [comment]
@AKalinich-Luxoft can this issue be closed based on your last comment?

**Comment by JackLivio** [comment]
@jordynmackool @AKalinich-Luxoft I confirmed that the timer stops when it is supposed to. The other details of the issue related to the progress bar will be implemented by https://github.com/smartdevicelink/sdl_hmi/pull/166
