### ISSUE TITLE
HMI selects wrong default vehicle emulation type

### ISSUE THREAD

**Issue by AKalinich-Luxoft** [smartdevicelink/sdl_hmi#240]
After including of feature [[SDL 0221] Remote Control - Allow Multiple Modules per Module Type"](https://github.com/smartdevicelink/sdl_hmi/issues/198) into the release 6.0, new SDL is now working with the `SystemCapabilities` with included [`moduleId` mandatory field](https://github.com/smartdevicelink/sdl_core/blob/518df4697965ba6481932af3a9f77b1bd49487f0/src/components/interfaces/HMI_API.xml#L1677). However, `no emulation` mode on HMI was designed to test older SDL versions which are not supporting this feature and working without `moduleId`.

In order to make latest HMI to be on the same page with SDL, emulation mode should be enabled by default. This may simplify work with HMI as tester does not need to change emulation mode each time on each HMI start. It makes more sense to disable emulation when it is not needed, but in most cases it is needed by default.

**Preconditions:**
1. SDL and HMI are started

**Step:**
1. Click "Vehicle" button
2. Check for currently selected vehicle emulation type

**Expected result:**
Vehicle 2x3 or vehicle 3x3 mode should be selected

**Actual result:**
No emulation mode is selected

**Comment by AKalinich-Luxoft** [comment]
Luxoft team is preparing a fix

**Comment by AKalinich-Luxoft** [comment]
@theresalech Please triage this issue

**Comment by iCollin** [comment]
Closed via #239
