### ISSUE TITLE
AlertIcon: HMI does not send “resultCode”:”WARNINGS” in case Requested image(s) not found

### ISSUE THREAD

**Issue by Ypostolov** [smartdevicelink/sdl_hmi#243]
**Preconditions:**
1. SDL and HMI are started
2. SPT is registered and activated on HMI
3. The  <iconnn.png> does NOT exists in app sub-directory of "AppStorageFolder" (the value defined at .ini file)

**Steps:**
1. App sends AlertIcon:
"Alert"( "alertIcon": {
       "isTemplate": true,
       "value": "iconnn.png",
       "imageType": "DYNAMIC"
}
2. Soft button ”Close” pressed. 

**Expected result:**
1. HMI sends to SDL:
result":{"code":21,"method":"UI.Alert", info: Requested image(s) not found}

2. SDL sends to MOB:
(“resultCode”:”WARNINGS”, '’success”:true, info: Requested image(s) not found.)

**Actual result:**
1. HMI sends to SDL 
result":{"code":0,"method":"UI.Alert"}

2. SDL sends to MOB
(“resultCode”:”SUCCESS”, '’success”:true)

**Attachment:**
[HMI_&_SDL_logs_HMI_screen.tar.gz](https://github.com/smartdevicelink/sdl_hmi/files/3720406/HMI_._SDL_logs_HMI_screen.tar.gz)

**Comment by aderiabin** [comment]
@theresalech, Please triage this issue.
Luxoft team has provided a fix already.
