### ISSUE TITLE
AddCommands are failing randomly with a `GENERIC_ERROR` result code

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_hmi#246]
When I send a bunch of `AddCommands` with the SDL_iOS Swift Example app, some of them fail randomly with a `GENERIC_ERROR` result code.

```
2019-10-15 14:04:41.638337 SDL Example Swift[23951:982459] [Dispatcher] Request failed: AddCommand (request), id: 52
{
    cmdID = 23;
    menuParams = "{\n    menuName = Odometer;\n    parentID = 2;\n    position = 20;\n}";
}, response: AddCommand (response), id: 52
{
    info = "UI component does not respond";
    resultCode = "GENERIC_ERROR";
    success = 0;
},
```

**Comment by iCollin** [comment]
I've sent 2000 AddCommand RPCs (in batches of 500) without one failing.
Can you please provide some more info on what you were doing when you saw this?

**Comment by NicoleYarroch** [comment]
I think I've figured out how to reproduce this issue. When I start a fresh session of core, this bug never occurs, but if I close the mobile app session (by clicking on the "disconnect" button in the SDL_iOS Swift app) and then open a new session with the same core session (By clicking on the "connect" button in the SDL_iOS Swift app) then I can usually get the bug to occur.

**Comment by iCollin** [comment]
Thank you for reporting!
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/251
