### ISSUE TITLE
Setting read-only param in remote control data returns successful response

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_hmi#252]
When the app sets the read-only `CurrentTemperature` param in `ClimateControlData` and sets another param that is not read-only in the same request, the app gets a successful response even though the read-only param is not set. 

This is a sample code that shows the issue:

```
ModuleData moduleData = new ModuleData(ModuleType.CLIMATE);
ClimateControlData climateControlData = new ClimateControlData();
climateControlData.setCurrentTemperature(new Temperature(TemperatureUnit.FAHRENHEIT, 77f));
climateControlData.setDesiredTemperature(new Temperature(TemperatureUnit.FAHRENHEIT, 66f));
moduleData.setClimateControlData(climateControlData);
SetInteriorVehicleData setInteriorVehicleData = new SetInteriorVehicleData(moduleData);
setInteriorVehicleData.setOnRPCResponseListener(new OnRPCResponseListener() {
    @Override
    public void onResponse(int correlationId, RPCResponse response) {
        try {
            Log.i(TAG, "onResponse: " + response.serializeJSON().toString());
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onError(int correlationId, Result resultCode, String info) {
        super.onError(correlationId, resultCode, info);
        Log.i(TAG, "onError: " + " resultCode: " + resultCode + " info: " + info);

    }
});
sdlManager.sendRPC(setInteriorVehicleData);
```

It is expected to get an error or warning message to let the app know that the read-only param was not set correctly in that case.

**Comment by JackLivio** [comment]
@bilal-alsharifi This is actually a behavior built into Core and not an HMI issue. If there is an RC request that contains read only params + other non readonly params, Core will filter those read only parameters out and continue processing the rest of the message. This is expected behavior.
