### ISSUE TITLE
OnLanguageChange and OnSystemInfoChanged are sent twice

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#256]
### Bug Report
OnLanguageChange and OnSystemInfoChanged are sent twice

##### Reproduction Steps
1. SDL and HMI are started
2. App is registered
3. Change language on HMI

##### Expected Behavior
HMI sends OnLanguageChange and OnSystemInfoChanged once to SDL

##### Observed Behavior
```
FFW.UI.OnLanguageChange
RPCClient.js:317 HMI -> SDL [15:17:6:13]: {"jsonrpc":"2.0","method":"UI.OnLanguageChange","params":{"language":"DE-DE"}}
BasicCommunicationRPC.js:1036 FFW.BasicCommunication.OnSystemInfoChanged
RPCClient.js:317 HMI -> SDL [15:17:6:17]: {"jsonrpc":"2.0","method":"BasicCommunication.OnSystemInfoChanged","params":{"language":"DE-DE"}}
UIRPC.js:1589 FFW.UI.OnLanguageChange
RPCClient.js:317 HMI -> SDL [15:17:6:20]: {"jsonrpc":"2.0","method":"UI.OnLanguageChange","params":{"language":"DE-DE"}}
BasicCommunicationRPC.js:1036 FFW.BasicCommunication.OnSystemInfoChanged
RPCClient.js:317 HMI -> SDL [15:17:6:22]: {"jsonrpc":"2.0","method":"BasicCommunication.OnSystemInfoChanged","params":{"language":"DE-DE"}}
RPCClient.js:137 SDL -> HMI [15:17:6:126]: {"id":262,"jsonrpc":"2.0","method":"BasicCommunication.UpdateAppList","params":{"applications":[]}}
```

##### OS & Version Information
* SDL: https://github.com/smartdevicelink/sdl_core/tree/release/6.0.0 (tag RC_2)
https://github.com/smartdevicelink/sdl_core/tree/develop
* HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop
(bd53f11339ee4d95a41caf5e5edf4ae0839d5957)
* SPT: https://rink.hockeyapp.net/apps/dbc7db5274027027262185753824e34d
Version 20191028-Nightly-Android (1034)

**Comment by YarikMamykin** [comment]
@theresalech Please triage this issue and notice linked fix is ready for review.

**Comment by jacobkeeler** [comment]
Closing with the merge of #263
