### ISSUE TITLE
HMI doesn't show in console log BC.OnSystemCapabilityUpdated and AS.OnAppServiceData notifications sent from SDL

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_hmi#257]
According to HMI API `BC.OnSystemCapabilityUpdated` and `AS.OnAppServiceData` notifications are bi-directional and can be sent from/or to SDL.
Currently HMI doesn't show in console notifications which are sent from SDL.
Seeing these messages will be very helpful during manual testing of App Services

**Comment by dboltovskyi** [comment]
@theresalech Please triage this issue and notice linked fix is ready for review.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/258
