### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_hmi#259]
### Bug Report
Uncaught TypeError

##### Reproduction Steps
1. Hit `Put File`
2. Tap `...` next to the `Local File Name` field
3. Select a photo on your phone
4. Leave file type as `GRAPHIC_BMP`
6. Hit SEND
7. Hit `DeleteFile`
8. Select from dropdown list file
9. Hit SEND

##### Expected Behavior
In the console of HMI does not displayed error after successful delete of file

##### Observed Behavior
In the console see Uncaught TypeError after successful delete of file

##### OS & Version Information
SDL: https://github.com/smartdevicelink/sdl_core/tree/release/6.0.0 (4d283e6)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop
(commit: bd53f11339ee4d95a41caf5e5edf4ae0839d5957) 

##### Attachments
[error in the HMI console.tar.gz](https://github.com/smartdevicelink/sdl_hmi/files/3845882/error.in.the.HMI.console.tar.gz)

**Comment by YarikMamykin** [comment]
@theresalech Please triage this issue and notice linked fix is ready for review.

**Comment by theresalech** [comment]
Closed via #260
