### ISSUE TITLE
HMI doesn't provide `url` and `appID` in BC.OnSystemRequest

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_hmi#278]
**Steps:**
0. SDL is built in `EXTERNAL_PROPRIETARY` mode
1. Start SDL, HMI, connect Mobile
2. Register new App
=> PTU is trigerred 
3. Wait until HMI starts to send `BC.OnSystemRequest` notifications
4. Check data

**Expected:**
There `url` and `appID` parameters are present in notification

**Actual:**
There are no `url` and `appID` parameters

**Comment by jacobkeeler** [comment]
Closing with the merge of #279
