### ISSUE TITLE
Create Widgets Button causes the HMI to crash

### ISSUE THREAD

**Issue by daishah** [smartdevicelink/sdl_hmi#281]
### Reproduction Steps
1.   Connect to HMI
2.   Click Create Widget Button on Phone
3.   Click 2nd Create Livio Button
4.   Click Add Widget
5.   Add Widget (Dismiss Pop up if it displays) (edited) 
6.   Click 1st Create Livio Button
7.   HMI Crashes

### Expected Behavior
When clicking the 1st Create Livio Button (after clicking the 2nd Create Livio Button) should not Crash the HMI – NOTE: Per Development – HMI hasn’t ever crashed before as a result of any testing

 ### Observed Behavior
When clicking the 1st Create Livio Button (after clicking the 2nd Create Livio Button) crashes the HMI
 
### OS & Version Information
 * OS/Version: Android 10 (Google Pixel 3), Catalina 10.15.3
 * SDL Core Version – Core 6.0
* Testing Against - SDL HMI, Test Suite

 Chrome experiences an out of memory crash - Screen Shot 2020-03-09 at 2.23.30 P
![Screen Shot 2020-03-09 at 2 23 30 PM](https://user-images.githubusercontent.com/57497476/76245407-37018000-6212-11ea-8bda-f09a70fc262c.png)

**Comment by iCollin** [comment]
Fixed in #282
