### ISSUE TITLE
Alert RPC ignores app priority

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_hmi#290]
According to the Core Certification Guidelines (found here: https://smartdevicelink.com/resources/, Smoke Test - 29), Alerts are supposed to take app priority into account. If an app with a higher priority (determined by its priority value position in the `AppPriority` enum [defined here](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/HMI_API.xml#L1449-L1456)), sends an Alert while an app of lower priority has an Alert active, the lower priority app should be sent an `ABORTED` response and the higher priority app's alert should take precedence.

Reproduction steps:
1. Connect app1 with `Notifications` permissions (allowing `Alert` RPC in background) and priority `NORMAL`, both configurable in the policy table for this app.
2. Connect app2 with `Notifications` permissions and priority `COMMUNICATION`.
3. Activate app2
4. Return to app menu, activate app1 (putting app2 into `BACKGROUND` HMI level)
5. Send `Alert` RPC from app1, alert appears on-screen
6. While the first alert is active, send `Alert` request from app2

Expected Behavior:
1. First alert is dismissed, app1 received `Alert` response with `ABORTED`
2. app2's alert appears on-screen

Actual Behavior:
1. First alert remains active, app2 receives `Alert` response with `REJECTED`

**Comment by ShobhitAd** [comment]
Closed via #298
