### ISSUE TITLE
TypeError by file deleting

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#300]
### Bug Report
TypeError by file deleting

##### Reproduction Steps
1. Start SDL and HMI
2. Mobile app adds file by PutFile RPC
3.Some RPC is processed with added file
4. Mobile app requests DeleteFile

##### Expected Behavior
HMI receives BC.OnFileRemoved and there are no error messages in HMI console

##### Observed Behavior
HMI receives BC.OnFileRemoved and logs the error
```
TypeError: SDL.SDLController.getApplicationModel(...).globalProperties.vrHelp[i].image is undefinedModel.js:353:1
    onFileRemoved file:///home/developer/sdl/repo/SDLMirror/sdl_hmi/app/model/sdl/Abstract/Model.js:353
    onRPCNotification file:///home/developer/sdl/repo/SDLMirror/sdl_hmi/ffw/BasicCommunicationRPC.js:431
    d Ember
    onWSMessage file:///home/developer/sdl/repo/SDLMirror/sdl_hmi/ffw/RPCClient.js:168
    onmessage file:///home/developer/sdl/repo/SDLMirror/sdl_hmi/ffw/RPCClient.js:81
```

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e8baa2d8f3f4b43d261323e0dd2c30843509e925
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

##### HMI log
[hmi.log](https://github.com/smartdevicelink/sdl_hmi/files/4425673/hmi.log)

**Comment by AKalinich-Luxoft** [comment]
@theresalech PR with fix is ready for Livio review.
Please note, this is NOT a regression issue found by Luxoft during release manual testing.

**Comment by theresalech** [comment]
Hi @AKalinich-Luxoft, thanks for reporting. At this time, our team is focused on final testing in preparation for next week's releases. We will include this PR if time allows, and will otherwise make note of the issue for a future release.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/332
