### ISSUE TITLE
HMI should use PLAY_PAUSE button name instead of OK

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#301]
### Bug Report
HMI shold use PLAY_PAUSE button name instead of OK

##### Reproduction Steps
1. Start SDL and HMI
2. Press `OK` button on HMI

##### Expected Behavior
Physical name for `OK` button should be updated to `PLAY_PAUSE` starting from release 5.0.
HMI sends `Buttons.OnButtonEvent` and `Buttons.OnButtonPress` with button name =`PLAY_PAUSE`

##### Observed Behavior
HMI sends `Buttons.OnButtonEvent` and `Buttons.OnButtonPress` with button name =`OK`

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e8baa2d8f3f4b43d261323e0dd2c30843509e925
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Comment by AKalinich-Luxoft** [comment]
@theresalech PR with fix is ready for Livio review

**Comment by iCollin** [comment]
Closed by #333
