### ISSUE TITLE
Unsupported externalTemperature value

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#302]
### Bug Report
Unsupported `externalTemperature` value

##### Reproduction Steps
1. Start SDL and HMI
2. Go to `Vehicle Info` -> `Edit Vehicle Data`

##### Expected Behavior
`externalTemperature` has value according to API. All `VehicleData` requests with `externalTemperature` are processed successfully.

##### Observed Behavior
`externalTemperature` has value null what is invalid according to API. All `VehicleData` requests with `externalTemperature` are processed unsuccessfully.

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e8baa2d8f3f4b43d261323e0dd2c30843509e925
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Comment by AKalinich-Luxoft** [comment]
@theresalech PR with fix is ready for Livio review.
Please note, this is NOT a regression issue found by Luxoft during release manual testing.

**Comment by theresalech** [comment]
Hi @AKalinich-Luxoft, thanks for reporting. At this time, our team is focused on final testing in preparation for next week's releases. We will include this PR if time allows, and will otherwise make note of the issue for a future release.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/334
