### ISSUE TITLE
HMI does not send SetAppProperties request on press Set button on HMI

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#303]
### Bug Report
HMI does not send SetAppProperties request on press Set button on HMI

##### Reproduction Steps
1) SDL and HMI are started"
2) On HMI → Apps →Apps Store → Set Apps Properties → Set
{nicknames: { "StringNicknames"},
policyAppID:"StringAppID", 
enabled: ***true***,
transportType:"ws", 
hybridAppPreference: "BOTH"}

2) On HMI → Apps →Apps Store → Set Apps Properties → Set
{nicknames: { "StringNicknames" },
policyAppID:"StringAppID", 
enabled: ***false***, 
transportType:"ws",
hybridAppPreference: "BOTH" }

3) On HMI → Apps →Apps Store → Set Apps Properties → Set
{nicknames: { "StringNicknames" }
policyAppID:"StringAppID",
enabled: ***true***,
transportType:"ws",
hybridAppPreference: "BOTH" }

Expected Results:
1) HMI → SDL: SetAppProperties ( properties: {nicknames: { "StringNicknames" }
policyAppID:"StringAppID",  enabled: ***true***, transportType:"ws",  hybridAppPreference: "BOTH" })
2) HMI → SDL: SetAppProperties ( properties: {nicknames: { "StringNicknames" }
policyAppID:"StringAppID",  enabled: ***false***,  transportType:"ws",  hybridAppPreference: "BOTH" })
3) HMI → SDL: SetAppProperties ( properties:{nicknames:{ "StringNicknames" }
policyAppID:"StringAppID",  enabled: ***true***,  transportType:"ws",  hybridAppPreference: "BOTH" })
 
Actual Results:
1) HMI → SDL: SetAppProperties ( properties: {nicknames:  { "StringNicknames" } policyAppID:"StringAppID",
enabled: ***true***,  transportType:"ws",  hybridAppPreference: "BOTH" })
2) HMI → SDL: SetAppProperties ( properties:{nicknames: { "StringNicknames" } policyAppID:"StringAppID", 
enabled: ***false***,  transportType:"ws",  hybridAppPreference: "BOTH" })
3) HMI does not send SetAppProperties request on press Set button on HMI

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: 74d24927cf77282c44678eba219adadbb6dcd072
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Comment by AKalinich-Luxoft** [comment]
@theresalech PR with fix is ready for Livio review.
Please note, this is NOT a regression issue found by Luxoft during release manual testing.

**Comment by theresalech** [comment]
Hi @AKalinich-Luxoft, thanks for reporting. At this time, our team is focused on final testing in preparation for next week's releases. We will include this PR if time allows, and will otherwise make note of the issue for a future release.

**Comment by iCollin** [comment]
Closed via #304
