### ISSUE TITLE
HMI provides all CLIMATE data in case climateEnable=false

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#305]
### Bug Report
HMI provides all `CLIMATE` data in case `climateEnable=false`

##### Reproduction Steps
1. Start SDL and HMI
2. `REMOTE_CONTROL` app is registered
3. Go to tab `Climate` and press `Climate OFF` button for a turning off 
4. Mobile app requests `GetInteriorData(subscription=false)`

##### Expected Behavior
HMI responds with only climateEnable=false parameter:

> HMI -> SDL : {"jsonrpc":"2.0","id":332,"result":{"code":0,"method":"RC.GetInteriorVehicleData","moduleData":{"moduleType":"CLIMATE","moduleId":"d38e4a05-b17c-28e3-9d38-e4a05b17c28e","climateControlData":{"climateEnable":false}}}}

##### Observed Behavior
HMI sends all `CLIMATE` data: 

> HMI -> SDL : {"jsonrpc":"2.0","id":332,"result":{"code":0,"method":"RC.GetInteriorVehicleData","moduleData":{"moduleType":"CLIMATE","moduleId":"d38e4a05-b17c-28e3-9d38-e4a05b17c28e","climateControlData":{"fanSpeed":0,"currentTemperature":{"unit":"CELSIUS","value":20},"desiredTemperature":{"unit":"CELSIUS","value":25},"acEnable":true,"circulateAirEnable":true,"autoModeEnable":true,"defrostZone":"FRONT","dualModeEnable":true,"acMaxEnable":true,"ventilationMode":"UPPER","heatedWindshieldEnable":false,"heatedRearWindowEnable":false,"heatedSteeringWheelEnable":false,"heatedMirrorsEnable":false,"climateEnable":false}}}}

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e8baa2d8f3f4b43d261323e0dd2c30843509e925
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Comment by AKalinich-Luxoft** [comment]
@theresalech PR with fix is ready for Livio review.
Please note, this is NOT a regression issue found by Luxoft during release manual testing.

**Comment by theresalech** [comment]
Hi @AKalinich-Luxoft, thanks for reporting. At this time, our team is focused on final testing in preparation for next week's releases. We will include this PR if time allows, and will otherwise make note of the issue for a future release.

**Comment by iCollin** [comment]
Closed via #335
