### ISSUE TITLE
HMI sends response with WARNINGS resultCode in case requested vehicle data is available 

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#306]
**Bug Report**
HMI sends response with WARNINGS resultCode in case requested vehicle data is available

**Reproduction Steps**

   1. Start SDL, HMI, connect Mobile, register new App
   2. Send SubscribeVehicleData with speed = true
   3.  Send UnsubscribeVehicleData with speed = true

**Expected Behavior**

  1. HMI sends response to SDL:"{"jsonrpc":"2.0","id":58,"result":{"speed": {"dataType":"VEHICLEDATA_SPEED","resultCode":"SUCCESS"}, "code":0,"method":"VehicleInfo.SubscribeVehicleData"}}"
  2. HMI sends response to SDL: "{"jsonrpc":"2.0","id":60,"result":{"speed": {"dataType":"VEHICLEDATA_SPEED","resultCode":"SUCCESS"}
 ,"code":0,"method":"VehicleInfo.UnsubscribeVehicleData"}}"

**Observed Behavior**
1. HMI sends response to SDL:"{"jsonrpc":"2.0","id":58,"result":{"speed": {"dataType":"VEHICLEDATA_SPEED","resultCode":"SUCCESS"}
 , "code":21,"method":"VehicleInfo.SubscribeVehicleData"}}"
2. HMI sends response to SDL: "{"jsonrpc":"2.0","id":60,"result":{"speed": {"dataType":"VEHICLEDATA_SPEED","resultCode":"SUCCESS"}
,"code":21,"method":"VehicleInfo.UnsubscribeVehicleData"}}"

**OS & Version Information**
    sdl_hmi branch: develop
    commit: e5743af
    sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Comment by theresalech** [comment]
Closed via #311
