### ISSUE TITLE
HMI does not show the Alert icon any more after unsuccessful attempt

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#307]
### Bug Report
HMI does not show the Alert icon any more after unsuccessful attempt

##### Reproduction Steps
1. Start SDL and HMI
2. Alert is requested with the not available icon
3. HMI returns WARNINGS resultCode
4. Alert is requested with the available icon

##### Expected Behavior
HMI shows Alert pop-up with required icon.

##### Observed Behavior
Error is shown during first Alert
> GET file:///home/igetmanets/sdl/builds/release_6_1_RC/p/bin/storage/584421907_7a6402a6c573b4bc9259a92ee99310589b09df4f1cd1e636eba171097c0af1a8/icon.pngg?m=1586331642240 net::ERR_FILE_NOT_FOUND

HMI shows Alert pop-up without the required icon.

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e8baa2d8f3f4b43d261323e0dd2c30843509e925
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Comment by AKalinich-Luxoft** [comment]
@theresalech PR with fix is ready for Livio review.
Please note, this is a regression issue found by Luxoft during release manual testing.

**Comment by theresalech** [comment]
Hi @AKalinich-Luxoft, thanks for reporting. At this time, our team is focused on final testing in preparation for next week's releases. We will include this PR if time allows, and will otherwise make note of the issue for a future release.

**Comment by iCollin** [comment]
Closed via #336
