### ISSUE TITLE
TypeError by OnAppServiceData notification

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#308]
**Bug Report**
TypeError by OnAppServiceData notification

**Reproduction Steps**
1. Start SDL and HMI
2. App successfully published service:
{.. "serviceName" : "WeatherServiceProvider", "serviceType" : "WEATHER",..}

3. App sends OnAppServiceData (“serviceData” : <WeatherServiceProvider service data>)

**Expected Behavior**
1. HMI receives "AppService.OnAppServiceData" and there are no error messages in HMI console

**Observed Behavior**
1 .HMI receives "AppService.OnAppServiceData"and logs the error

RPCClient.js:150 Uncaught TypeError: Cannot read property 'checkImage' of undefined
at d.onWSMessage (RPCClient.js:150)
at WebSocket.socket.onmessage (RPCClient.js:81)

**OS & Version Information**
sdl_hmi branch: develop
commit: e5743af
sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

Report and Logs: 
[SDL_HMI_logs.zip](https://github.com/smartdevicelink/sdl_hmi/files/4451192/SDL_HMI_logs.zip)

**Comment by AKalinich-Luxoft** [comment]
@theresalech PR with fix is ready for Livio review.
Please note, this is a regression issue found by Luxoft during release manual testing.

**Comment by theresalech** [comment]
Hi @AKalinich-Luxoft, thanks for reporting. At this time, our team is focused on final testing in preparation for next week's releases. We will include this PR if time allows, and will otherwise make note of the issue for a future release.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/337
