### ISSUE TITLE
HMI renews Channel Set for current shown id only after switching screen to another item

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#309]
### Bug Report
HMI renews `Channel Set` for current shown id only after switching screen to another item and back

##### Reproduction Steps
1. SDL and HMI are started
2. `REMOTE_CONTROL` app is registered and activated
3. Open `Audio` pop-up
4. Current shown channel is 1
5. Mobile app requests `SetInteriorVehicleData`(update `equalizerSettings` for channel id=1)

##### Expected Behavior
HMI update `Channel Set` for id 1 on `Audio` pop-up after receiving `RC.SetInteriorVehicleData` request

##### Observed Behavior
HMI renews `Channel Set` for id 1 on `Audio` pop-up only after switching current `equalizerSettings` item to another item and back

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e8baa2d8f3f4b43d261323e0dd2c30843509e925
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Comment by iCollin** [comment]
Closed via #338
