### ISSUE TITLE
HMI sends displayMode=AUTO in OnInteriotVehicleData notif and SetInteriorVehicleData response

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#310]
### Bug Report
HMI sends `displayMode=AUTO` in `OnInteriotVehicleData` notification and `SetInteriorVehicleData` response

##### Reproduction Steps
1. Start SDL and HMI
2. `REMOTE_CONTROL` app is registered and activated
3. Go to `Settings` - > `HMI`
4. Current `Display mode` is set to `DAY` or `NIGHT`
5. Mobile app requests `SetInteriorVehicleData(displayMode=AUTO)`

##### Expected Behavior
The mode used by the HMI is either DAY or NIGHT. 
Currently auto mode for HMI is `DAY`, so HMI set `AUTO` value on HMI settings tab and sends `OnInteriotVehicleData(displayMode=DAY)`,  `SetInteriorVehicleData(displayMode=DAY)` response

##### Observed Behavior
HMI sends `displayMode=AUTO` in `OnInteriotVehicleData` notification and `SetInteriorVehicleData` response 

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e8baa2d8f3f4b43d261323e0dd2c30843509e925
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

##### Logs
[hmi_log.zip](https://github.com/smartdevicelink/sdl_hmi/files/4455144/hmi_log.zip)

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/322
