### ISSUE TITLE
HMI sends OnInteriorVehicleData notification with incorrect type of frequencyInteger on press XM radio preset button on HMI

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#312]
**Bug Report**

HMI sends OnInteriorVehicleData notification with incorrect type of frequencyInteger on press XM radio preset button on HMI

**Reproduction Steps**   
1. Start SDL, HMI, connect Mobile, register new App (REMOTE_CONTROL)
2. App succesfully subscribed to module RADIO: GetInteriorVehicleData {moduleType: Radio, subscribe:true}
3. Set current band - XM on HMI
4. Press "preset_1" button on HMI

**Expected Behavior**
1. HMI sends OnInteriorVehicleData notification {..radioControlData":{"frequencyInteger":1}}... }  to  SDL
2. SDl sends  OnInteriorVehicleData notification {..radioControlData":{"frequencyInteger":1}}... } to Mobile App

**Observed Behavior**
1. HMI sends OnInteriorVehicleData notification  /{..radioControlData":{"**frequencyInteger":null**}}... } to  SDL
2. SDl does not send  OnInteriorVehicleData notification

**OS & Version Information**
    sdl_hmi branch: develop
    commit: e5743af
    sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Logs**
[SDL_HMI_logs.zip](https://github.com/smartdevicelink/sdl_hmi/files/4457833/SDL_HMI_logs.zip)

**Comment by Ypostolov** [comment]
@theresalech PR with fix is ready for Livio review

**Comment by iCollin** [comment]
Closed by #341
