### ISSUE TITLE
HMI sends BC.OnSystemRequest notification without requestType: "PROPRIETARY"

### ISSUE THREAD

**Issue by TMyza** [smartdevicelink/sdl_hmi#313]
**Bug Report**

HMI sends BC.OnSystemRequest notification without requestType: "PROPRIETARY"

**Reproduction Steps**   
1. Start SDL, HMI, connect Mobile
2. App is consented and activated

**Expected Behavior**
1. HMI sends BC.OnSystemRequest notification with requestType

**Observed Behavior**
1. HMI sends BC.OnSystemRequest notification without requestType several times
(due to notifications, SDL counts retries for PTU incorrect)

**OS & Version Information**
    sdl_hmi branch: develop
    commit: e5743af
    sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Logs**
[SmartDeviceLinkCore.log](https://github.com/smartdevicelink/sdl_hmi/files/4463134/SmartDeviceLinkCore.log)

[HMI_log.txt](https://github.com/smartdevicelink/sdl_hmi/files/4463151/HMI_log.txt)

**Comment by AKalinich-Luxoft** [comment]
@theresalech PR with fix is ready for Livio review.
Please note, this is a regression issue found by Luxoft during release manual testing.

**Comment by theresalech** [comment]
Hi @AKalinich-Luxoft, thanks for reporting. At this time, our team is focused on final testing in preparation for next week's releases. We will include this PR if time allows, and will otherwise make note of the issue for a future release.

**Comment by jacobkeeler** [comment]
Closed via #366
