### ISSUE TITLE
HMI does not send resultCode: "WARNINGS" + "message: Requested image(s) not found" from HMI in case Image is invalid

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#314]
**Bug Report**
HMI does not send resultCode: "WARNINGS" + "message: Requested image(s) not found" from HMI in case Image is invalid

The following RPCs are impacted:  FAILED
1. SendLocation
2. ShowConstantTBT
3. Show
4. AddSubMenu
5. AddCommand
6. SetGlobalProperties
7. UpdateTurnList
8. PerformInteraction
9. AlertManeuver
10. ShowConstantTBT
11. ScrollableMessage

**Reproduction Steps**

1. Start SDL, HMI, connect Mobile, register new App
2. The <missed_icon.png> does NOT exists at app sub-directory of "AppStorageFolder" (the value defined at .ini file)
3. Mobile app requests AddCommand with image that is absent on file system: MOB->SDL: ("AddCommand"
    {...CmdIcon = { value ="*missed_icon.png*", imageType ="DYNAMIC"}  … })

**Expected Behavior**

1. SDL->HMI:  “UI.AddCommand", { ...cmdIcon = { value ="missed_icon.png",imageType ="DYNAMIC" }..}
2. The AddCommand without icon is displayed on HMI.
3. HMI -> SDL: result":{"code":21,"method":"UI.AddCommand", info: Requested image(s) not found}}
4. SDL -> MOB: AddCommand (“resultCode”:”WARNINGS”, '’success”:true, info: Requested image(s) not found.

**Observed Behavior**

1. SDL->HMI:  “UI.AddCommand", {{ ...cmdIcon =
{ value ="missed_icon.png",imageType ="DYNAMIC" }..})
2. The AddCommand without icon is displayed on HMI.
3. HMI -> SDL: result":{"code":0,"method":"UI.AddCommand"}}
4. SDL -> MOB: AddCommand (“resultCode”:”SUCCESS”, '’success”:true)
 
**OS & Version Information**
sdl_hmi branch: develop
commit: e5743af
sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Logs:**
[HMI_logs.zip](https://github.com/smartdevicelink/sdl_hmi/files/4469679/HMI_logs.zip)

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/344
