### ISSUE TITLE
HMI is unable to send OnExitApplication with ApplicationExitReason : CLOSE_CLOUD_CONNECTION

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#316]
**Bug Report**
HMI is unable to send OnExitApplication  with  ApplicationExitReason : CLOSE_CLOUD_CONNECTION
HMI does not contain UI control button to EXIT Application with reason "CLOSE_CLOUD_CONNECTION"

**Reproduction Steps**

1. Start SDL, HMI, connect Mobile, register new App
2. Press button to EXIT Application with reason "CLOSE_CLOUD_CONNECTION"

**Expected Behavior**

1. HMI sends to SDL BC.OnExitApplication(CLOSE_ClOUD_CONNECTION)

**Observed Behavior**
   1. HMI does not contain UI control button to EXIT Application with reason "CLOSE_CLOUD_CONNECTION"

**OS & Version Information**
sdl_hmi branch: develop
commit: e5743af
sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/410
