### ISSUE TITLE
AlertManeuver pop-up displays the softButtons from previous requests

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#323]
### Bug Report
`AlertManeuver` pop-up displays the `softButtons` from previous requests

##### Reproduction Steps
1. Start SDL and HMI
2. Mobile app is registered and activated
3. App requests `AlertManeuver` with softButtons
4. First `AlertManeuver` request is successfully processed
5. App requests seconds `AlertManeuver` with softButtons

##### Expected Behavior
AlertManeuver pop-up is shown with the softButtons number defined in the request

##### Observed Behavior
![AlertManeuver](https://user-images.githubusercontent.com/11210973/79227795-22e01c80-7e69-11ea-8b01-d81e2a5945a5.png)

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e5743afe5193fcd9bc667d5d48a6220552345a97
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Comment by AKalinich-Luxoft** [comment]
@theresalech PR with fix is ready for Livio review.
Please note, this is a regression issue found by Luxoft during release manual testing.

**Comment by theresalech** [comment]
Hi @AKalinich-Luxoft, thanks for reporting. At this time, our team is focused on final testing in preparation for next week's releases. We will include this PR if time allows, and will otherwise make note of the issue for a future release.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/342
