### ISSUE TITLE
AlertManeuver pop-up does not display an softButton image 

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#324]
### Bug Report
`AlertManeuver` pop-up does not display an softButton image 

##### Reproduction Steps
1. Start SDL and HMI
2. Mobile app is registered and activated
3. App requests `AlertManeuver` with softButtons`(type=BOTH or IMAGE, image = { value = <some_image_name>, imageType=DYNAMIC })`

##### Expected Behavior
SoftButtons images are shown correctly on `AlertManeuver` pop-up

##### Observed Behavior
![AlertManeuver_image](https://user-images.githubusercontent.com/11210973/79228908-de558080-7e6a-11ea-81a9-81daec2041df.png)

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e5743afe5193fcd9bc667d5d48a6220552345a97
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Comment by AKalinich-Luxoft** [comment]
@theresalech PR with fix is ready for Livio review.
Please note, this is a regression issue found by Luxoft during release manual testing.

**Comment by theresalech** [comment]
Hi @AKalinich-Luxoft, thanks for reporting. At this time, our team is focused on final testing in preparation for next week's releases. We will include this PR if time allows, and will otherwise make note of the issue for a future release.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/343
