### ISSUE TITLE
Display mode is not applicable for POI list

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#326]
### Bug Report
Display mode is not applicable for `POI` list

##### Reproduction Steps
1. Start SDL and HMI
2. SendLocation is allowed by policies
3. Mobile app is registered and activated
4. App requests `SendLocation`
5. Request is processed successfully 
6. Go to `Navigation` tab -> `POI`
7. Change `Display mode` 

##### Expected Behavior
`POI` list view is updated according to selected `Display mode`
 
##### Observed Behavior
`POI` list view is not updated according to selected `Display mode`

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e5743afe5193fcd9bc667d5d48a6220552345a97
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Comment by jacobkeeler** [comment]
Closing with the merge of #369
