### ISSUE TITLE
Image is displayed right on the text on Alert soft buttons

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#327]
### Bug Report
Image is displayed right on the text on soft buttons

##### Reproduction Steps
1. Start SDL and HMI
2. SendLocation is allowed by policies
3. Mobile app is registered and activated
4. Alert with softButtons(type=BOTH, image={ value = <some_image_value>, imageType = DYNAMIC })

##### Expected Behaviour
HMI displays the image near the text

##### Observed Behaviour
![Alert_softButton_image](https://user-images.githubusercontent.com/11210973/79234692-5031c800-7e73-11ea-8d07-e6c1bad42f6d.png)

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e5743afe5193fcd9bc667d5d48a6220552345a97
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Comment by AKalinich-Luxoft** [comment]
@theresalech PR with fix is ready for Livio review.
Please note, this is a regression issue found by Luxoft during release manual testing.

**Comment by theresalech** [comment]
Hi @AKalinich-Luxoft, thanks for reporting.  At this time, our team is focused on final testing in preparation for next week's releases.  We will include this PR if time allows, and will otherwise make note of the issue for a future release.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/343
