### ISSUE TITLE
Image is displayed right on the text on POI items

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#328]
### Bug Report
Image is displayed right on the text on POI items

##### Reproduction Steps
1. Start SDL and HMI
2. SendLocation is allowed by policies
3. Mobile app is registered and activated
4. App requests `SendLocation`  with image

##### Expected Behaviour
HMI displays the image near the text

##### Observed Behaviour
![POI_images](https://user-images.githubusercontent.com/11210973/79234704-53c54f00-7e73-11ea-9d9d-32443f6034ba.png)

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e5743afe5193fcd9bc667d5d48a6220552345a97
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Comment by jacobkeeler** [comment]
Closing with the merge of #356
