### ISSUE TITLE
HMI does not perform predefined actions by clicking the custom softButtons on AlertManeuver pop-up

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#346]
### Bug Report
HMI does not perform predefined actions by clicking the custom softButtons on AlertManeuver  pop-up

##### Reproduction Steps
1. Start SDL and HMI
2. AlertManeuver is allowed by policies
3. Mobile app is registered and activated
4. App requests `AlertManeuver` with softButtons
5. Request is processed successfully by SDL and is resent to HMI
6. Press custom button

##### Expected Behavior
HMI shows AlertManeuver pop-up only with custom softButtons.
According to pressed button type HMI should perform the next actions:
`DEFAULT_ACTION` - Default action occurs.  Standard behavior (e.g. SoftButton clears overlay)
`STEAL_FOCUS` - The calling app's dialog or related event should clear and the app should be brought into HMI_FULL
`KEEP_CONTEXT` - Current system context is maintained.  An overlay is persisted even though a SoftButton has been pressed and the notification sent

##### Observed Behavior
AlertManeuver pop-up is shown with custom and system defined "Close" SoftButtons.
HMI sends only `Buttons.OnButtonEvent` and `Buttons.OnButtonPress` by pressing custom button and performs predefined actions only by pressing system defined "Close" SoftButton.

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e5743afe5193fcd9bc667d5d48a6220552345a97
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

**Comment by AKalinich-Luxoft** [comment]
@theresalech PR with fix is ready for Livio review.

**Comment by VjKlepikov** [comment]
Issue is reproduced on:
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (95d16aa)
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (9f61819)

**Comment by iCollin** [comment]
@VjKlepikov Thank you for noticing. I see the tag was removed from the soft buttons by accident in #393. I have submitted a fix if you don't mind reviewing: https://github.com/smartdevicelink/sdl_hmi/pull/447

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/447

**Comment by VjKlepikov** [comment]
@iCollin Issues are observed:
   1. AlertManeuver pop-up is shown with custom and system defined "Close" SoftButtons.
   2. HMI does not perform predefined actions by pressing system defined "KEEP_CONTEXT" SoftButton
New issue has been created [448](https://github.com/smartdevicelink/sdl_hmi/issues/448)
