### ISSUE TITLE
HMI shows SEAT paramers only for one moduleId

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#349]
### Bug Report
HMI shows SEAT paramers only for one moduleId

##### Reproduction Steps
1. SDL and HMI are started (HMI sends more than one moduleId in seat capabilities)
2. RC app is registered and activated
3. Go to HMI menu->Seat

##### Expected Behavior
HMI has a drop-down list with all moduleId values and according to value in the list shows parameters for the required moduleId.

##### Observed Behavior
HMI shows parameters only for one moduleId and there is no ability to select another one.
![image](https://user-images.githubusercontent.com/11210973/80502153-f2c06f80-8978-11ea-8d95-76f70a8ea4f4.png)

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC2
* HMI: https://github.com/smartdevicelink/sdl_hmi/commit/7a7e6acddc12b8b4e9d2b98df9c09ee423f6356d

**Comment by GetmanetsIrina** [comment]
This is not an regression issue, issues is reproduced on release 5.2.

**Comment by iCollin** [comment]
Closed by #381
