### ISSUE TITLE
AlertManeuver: SoftButton with an icon is not displayed in day/night/Highlighted mode

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_hmi#350]
Bug Report
**Reproduction Steps:**
1. SDL and HMI are started
2.  App is registered and in FULL HMILevel
3. App requests AlertManeuver with softButtons, (SoftButtont contains random image(Type: Both or Image)
4. On HMI select “Day mode” 
5. On HMI select “Night mode” 
6. On HMI select “Highlighted mode” 

**Expected result:**
1. The image is displayed in day mode
2. The image is displayed in night mode
3. The image is displayed in Highlighted mode
 
**Actual result:**
The image is not displayed in day/night/Highlighted mode

**OS & Version Information**
SDL: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC2 ceb4d9c
sdl_hmi branch: develop
commit: https://github.com/smartdevicelink/sdl_hmi/commit/7a7e6acddc12b8b4e9d2b98df9c09ee423f6356d

**Comment by Ypostolov** [comment]
Fixed in [#386](github.com/smartdevicelink/sdl_hmi/pull/368rl)

**Comment by Ypostolov** [comment]
@theresalech PR with fix is ready for Livio review.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/368
