### ISSUE TITLE
Error in the HMI console in case on HMI select Day/Night/Highlighted mode

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_hmi#351]
Bug Report
**Reproduction Steps:**
1. SDL and HMI are started
2. App(isMediaApplication = false) is registered and activated
3. On HMI select “Day mode”
4. On HMI select “Night mode”
5. On HMI select “Highlighted mode”

**Expected result:**
HMI console does not contain any errors

**Actual result:**
![Error in the HMI console](https://user-images.githubusercontent.com/34478015/80522078-a6832880-8994-11ea-970d-ee5e2cad1e26.png)

**OS & Version Information**
SDL: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC2 ceb4d9c
sdl_hmi branch: develop
commit: https://github.com/smartdevicelink/sdl_hmi/commit/7a7e6acddc12b8b4e9d2b98df9c09ee423f6356d

**Comment by iCollin** [comment]
Closed via #370
