### ISSUE TITLE
[SDL 0189] Restructuring OnResetTimeout

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_hmi#376]
Proposal: [Restructuring OnResetTimeout](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0189-Restructuring-OnResetTimeout.md)

> This proposal is to use OnResetTimeout for applicable interfaces so as to update the function and expand it to be used by a broader set of RPCs than just in _UI_ and _TTS_ interfaces.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/556

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with the following revisions: `extensionPeriod` will be renamed to `resetPeriod` and the proposal will address that HMI Integration Guidelines will need to be updated to call out that there is not currently version negotiation between HMI and Core, so older HMI implementations will not work with this new version of Core.
Lastly, it was noted that details of deprecating an HMI API will be determined upon implementation.

> The proposal .md file was updated to reflect these revisions on 7/26/18.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/575
