### ISSUE TITLE
HMI sends BasicCommunication.onReady notification two times

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#401]
**Bug Report**
HMI sends BasicCommunication.onReady notification two times

**Preconditions:**

1. HMI is started

**Reproduction Steps**

1. Start SDL

**Expected Behavior**

HMI sends BasicCommunication.onReady once
1. HMI -> SDL  {"method":"BasicCommunication.OnReady"}

**Observed Behavior**

HMI sends BasicCommunication.onReady notification two times

HMI -> SDL  {"method":"BasicCommunication.OnReady"}
HMI -> SDL  {"method":"BasicCommunication.OnReady"}
SDL sends IsReady requests to HMI for all applicable interfaces two times

**OS & Version Information**

OS/Version: Ubuntu 18.04
HMI: 6d32f1b

**Logs**
[SDL_HMI_logs.zip](https://github.com/smartdevicelink/sdl_hmi/files/5260406/SDL_HMI_logs.zip)

**Comment by VjKlepikov** [comment]
Issue is also applicable for HMI: 6.1_RC_2 https://github.com/smartdevicelink/sdl_hmi/tree/develop, commit: 7a7e6ac

**Comment by AKalinich-Luxoft** [comment]
@theresalech please notice PR with fix is ready for Livio review

**Comment by iCollin** [comment]
Closed via #400
