### ISSUE TITLE
HMI sends redundant "steeringWheelLocation" parameter in UI.GetCapabilities response

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#402]
**Bug Report**
HMI sends redundant "steeringWheelLocation" parameter in UI.GetCapabilities response

**Preconditions:**

1. HMI and SDL are started

**Reproduction Steps**

1. SDL sends UI.GetCapabilities request

**Expected Behavior**

1. HMI does not send UI.GetCapabilities response with "steeringWheelLocation" parameter 
UI.GetCapabilities : { ...  hmiCapabilities":{ "navigation":true, "phoneCall":true }}

**Observed Behavior**

1. HMI sends UI.GetCapabilities response with redundant "steeringWheelLocation" parameter 
UI.GetCapabilities : { ...  hmiCapabilities":{ "navigation":true, "phoneCall":true, **"steeringWheelLocation":"LEFT"** }}

OS & Version Information

OS/Version: Ubuntu 18.04
HMI: 6d32f1b

Logs
SDL_HMI_logs.zip

**Comment by VjKlepikov** [comment]
Issue is also applicable for HMI: 6.1_RC_2 https://github.com/smartdevicelink/sdl_hmi/tree/develop, commit: 7a7e6ac

**Comment by AKalinich-Luxoft** [comment]
@theresalech please notice PR with fix is ready for Livio review

**Comment by iCollin** [comment]
Closed via #399
