### ISSUE TITLE
HMI responds with WARNINGS code in case core requests AddCommand with image

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#409]
**Bug Report**
HMI responds with WARNINGS code in case core requests AddCommand with image

**Preconditions:**
1. HMI and SDL are started
2. Mobile app is registered and activated

**Reproduction Steps**
1. Mobile app requests AddCommand RPC with DYNAMIC image

**Expected Behavior**
HMI responds with SUCCESS resultCode to request with an existed and valid image

**Observed Behavior**
HMI responds with WARNINGS resultCode 

> SDL -> HMI [19:8:37:244]: {"id":144,"jsonrpc":"2.0","method":"UI.AddCommand","params":{"appID":135192773,"cmdID":5,"cmdIcon":{"imageType":"DYNAMIC","value":"/home/igetmanets/sdl/builds/DEVELOP/p/bin/storage/584421907_f49b554da6659cde038de40eff9f38f8d0f6f083b75a0d2466b82d54dacea2a0/icon.png"},"menuParams":{"menuName":"Item to Add 5","parentID":0,"position":0}}}

UIRPC.js:157 FFW.UI.onRPCRequest
AppModel.js:544 4
UIRPC.js:1702 FFW.UI.UI.AddCommandResponse
RPCClient.js:323 HMI -> SDL [19:8:37:253]: {"jsonrpc":"2.0","id":144,"result":{"code":21,"method":"UI.AddCommand"}}

**OS & Version Information**
OS: Ubuntu 18.04
SDL: https://github.com/smartdevicelink/sdl_core/commit/a36ea82740e648debf1b0367c24fed85d6ef2d80
HMI: https://github.com/smartdevicelink/sdl_hmi/commit/6d32f1ba10bd6d2335d755d902788fa82c6286e9
Mobile app: SPT 20200831-Android

**Comment by LitvinenkoIra** [comment]
@theresalech Please note, this is a regression issue found by Luxoft during release manual testing.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/344
