### ISSUE TITLE
HMI does not send SubtleAlert RPC related text fields and image fields as part of UI.GetCapabilities response

### ISSUE THREAD

**Issue by aderiabin** [smartdevicelink/sdl_hmi#413]
**Bug Report**
HMI does not send SubtleAlert RPC related text fields and image fields as part of UI.GetCapabilities response

**Occurrence:** always

**Reproduction Steps**
1. Start WebHMI and SDL

**Expected Behavior**
HMI sends UI.GetCapabilities response which contains `displayCapabilities` with
```
"textFields": [
  {
    "name": "subtleAlertText1",
    ...
  },
  {
    "name": "subtleAlertText2",
    ...
  },
  {
    "name": "subtleAlertSoftButtonText",
    ...
  } 
]
and "imageFields": [
  {
      "name": "subtleAlertIcon",
      ...
      }
  } 
]
```

**Observed Behavior**
HMI sends UI.GetCapabilities response which contains `displayCapabilities` without
next text fields: "subtleAlertText1", "subtleAlertText2", "subtleAlertSoftButtonText" and without "subtleAlertIcon" image field

(see attached logs)

**OS & Version Information**
OS/Version: Ubuntu 16.04
HMI: e4220d60e2bad9c1a83639992d79edcf0c2fd09

**Logs**
[HMI_log_no_SubtleAlert_fields_in_capabilities.log](https://github.com/smartdevicelink/sdl_hmi/files/5364910/HMI_log_no_SubtleAlert_fields_in_capabilities.log)
[SmartDeviceLinkCore.log.tar.gz](https://github.com/smartdevicelink/sdl_hmi/files/5364912/SmartDeviceLinkCore.log.tar.gz)

**Comment by jacobkeeler** [comment]
Closed via #421
