### ISSUE TITLE
Error response on DeleteSubMenu request for nested submenu in case of delete the top level submenu

### ISSUE THREAD

**Issue by AKalinich-Luxoft** [smartdevicelink/sdl_hmi#414]
Error response INVALID_ID on DeleteSubMenu request for nested submenu in case of delete the top level submenu

**Preconditions:**
1. SDL and HMI are started
2. Mobile device connected
3. Mobile app is registered and activated
4. SubMenu item is added
Send AddSubMenu("menuID":1, "menuName":"Submenu Name 1")
5. Nested submenu item are added (each submenu is nested in the previous submenu)
Send AddSubMenu(parentID=1, "menuID":2)
Send AddSubMenu(parentID=2, "menuID":3)
Send AddSubMenu(parentID=3, "menuID":4)

**Reproduction Steps:**
Delete submenu item (item is menu-tree branch)
Send DeleteSubMenu("menuID":2) request

APP→SDL: DeleteSubMenu ( "menuID":2 )

**Observed Behavior:**
1) SDL→HMI: UI.DeleteSubMenu ( params, "menuID":2)
HMI→SDL: UI.DeleteSubMenu ( resultCode = SUCCESS )

2) SDL→HMI: UI.DeleteSubMenu ( params, "menuID":4)
HMI→SDL: UI.DeleteSubMenu ( resultCode = SUCCESS )
SDL→HMI: UI.DeleteSubMenu ( params, "menuID":3)
HMI→SDL: { "error": { "code":13, "data": { "method":"UI.DeleteSubMenu " }}

3) SDL→APP: DeleteSubMenu ( "resultCode":"SUCCESS", "success":true )

Submenus are successfully removed
"Submenu Name 2" button is not displayed on HMI 
On HMI "Options" -> "Submenu Name 1"

**Expected Behavior:**
1) SDL→HMI: UI.DeleteSubMenu ( params, "menuID":2)
HMI→SDL: UI.DeleteSubMenu ( resultCode = SUCCESS )

2) SDL→HMI: UI.DeleteSubMenu ( params, "menuID":4)
HMI→SDL: UI.DeleteSubMenu ( resultCode = SUCCESS )
SDL→HMI: UI.DeleteSubMenu ( params, "menuID":3)
HMI→SDL: UI.DeleteSubMenu ( resultCode = SUCCESS )

3) SDL→APP: DeleteSubMenu ( "resultCode":"SUCCESS", "success":true )

Submenus are successfully removed
"Submenu Name 2" button is not displayed on HMI 
On HMI "Options" -> "Submenu Name 1"

**Comment by AKalinich-Luxoft** [comment]
@theresalech please note this is a regression issue related to release 7.0
PR with fix is ready for review and linked to the ticket

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/415
