### ISSUE TITLE
HMI does not send SubtleAlert RPC related text fields and image fields as part of BC.OnSystemCapabilityUpdated notification on app registration

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#429]
**Bug Report**
HMI does not send SubtleAlert RPC related text fields and image fields as part of BC.OnSystemCapabilityUpdated notification on app registration

**Preconditions:**
1. Start WebHMI and SDL
2. Connect mobile device
   
**Reproduction Steps**
1. Register app from mobile device

**Expected Behavior**
1. HMI sends BC.OnSystemCapabilityUpdated notification which contains `displayCapabilities` with
"textFields": [ { "name": "subtleAlertText1", ... }, { "name": "subtleAlertText2", ... }, { "name": "subtleAlertSoftButtonText", ... } ]
and "imageFields": [{ "name": "subtleAlertIcon",...}} ]

**Observed Behavior**
1. HMI sends BC.OnSystemCapabilityUpdated notification which contains `displayCapabilities` without
next text fields: "subtleAlertText1", "subtleAlertText2", "subtleAlertSoftButtonText" and without "subtleAlertIcon" image field

**OS & Version Information**
OS/Version: Ubuntu 16.04
SDL: https://github.com/smartdevicelink/sdl_core/tree/7.0.0-RC1 (5c72cdd)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (2cfbe48)

**Logs:**

**Comment by jacobkeeler** [comment]
Closed via #421
