### ISSUE TITLE
HMI does not show UI portion of PerformInteraction request

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#438]
**Bug Report**
HMI does not show UI portion of PerformInteraction request and responds immediately after request receiving

**Preconditions:**
1. Start WebHMI and SDL
2. Register mobile application
3. Activate the application
4. CreateInteractionChoiceSet is added

**Reproduction Steps:**
1. Send valid `PerformINteraction` RPC with `BOTH` or `MANUAL_ONLY` interaction mode
 
**Expected behavior:**
HMI shows UI portion of PerformInteraction request and waits for user actions

**Observed behavior:**
HMI does not show UI portion of PerformInteraction request and responds immediately after request receiving

**OS & Version Information**
OS: Ubuntu 18.04
SDL: https://github.com/smartdevicelink/sdl_core/commit/54246454
HMI: https://github.com/smartdevicelink/sdl_hmi/commit/931877c
SPT: 20201007

**Comment by GetmanetsIrina** [comment]
@ShobhitAd, looks like your fix https://github.com/smartdevicelink/sdl_hmi/pull/439 also fixes the current problem.

**Comment by ShobhitAd** [comment]
Closed via #439
