### ISSUE TITLE
HMI sends tryAgainTime parameter in SubtleAlert erroneous response

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#441]
**Preconditions:**
1. Start WebHMI and SDL
2. Connect the mobile device and consent it
3. Register app from the mobile device
4. Activate the app

**Reproduction Steps:**
1. Send SubtleAlert request from the app
2. Send another SubtleAlert request from the app during the duration of displaying of SubtleAlert RPC from the previous step

**Observed behavior:**
SDL sends SubtleAlert response which does not contain `tryAgainTime` parameter (see attached logs)

**Expected behavior:**
SDL sends SubtleAlert response which contains `tryAgainTime` parameter with the value which it received from HMI

**OS & Version Information**
SDL: https://github.com/smartdevicelink/sdl_core/commit/5c72cddc353aadef06e89064c53c1ec6b2467d25
HMI: https://github.com/smartdevicelink/sdl_hmi/commit/8495d9416076e5aa788e1c6b883fe97f9c443468

**Logs:**
[HMI_tryAgainTime_issue.log](https://github.com/smartdevicelink/sdl_hmi/files/5458266/HMI_tryAgainTime_issue.log)
[SmartDeviceLinkCore.log.tar.gz](https://github.com/smartdevicelink/sdl_hmi/files/5458267/SmartDeviceLinkCore.log.tar.gz)

**Comment by GetmanetsIrina** [comment]
Closing with the merge of #427

**Comment by GetmanetsIrina** [comment]
The issue is not fixed after merge on 
SDL: https://github.com/smartdevicelink/sdl_core/commits/release/7.0.0 (80973f45a1f137502521b24c26317e6391c08011)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (95d16aa)
Mobile app: 20201023

**Comment by GetmanetsIrina** [comment]
@theresalech Please note, this is a regression issue found by Luxoft during 7.0 release manual testing.

**Comment by theresalech** [comment]
@GetmanetsIrina please advise when Luxoft has a PR submitted to resolve the issue. However, as we are planning to release SDL 5.4 on November 5, 2020, we cannot guarantee that this PR will be included in the release.

**Comment by AKalinich-Luxoft** [comment]
@theresalech please note that PR with fix has been submitted and ready for Livio review

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/449
