### ISSUE TITLE
HMI responds with WARNINGS code in case core requests RPC with STATIC image type

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#442]
**Precondition:**
1. HMI and SDL are started
2. Mobile app is registered and activated

**Reproduction Steps:**
1. Mobile app requests Alert/ScrollableMessage/SendLocation/AddCommand/AlertManeuver/ShowConstantTBT/UpdateTurnList with `STATIC` image type ( in the main request or in softButton)

**Expected behavior:**
1. HMI processes the request, but not show the image
2. HMI responds with `UNSUPPORTED_RESOURCE` resultCode + the message of the kind `Image of '%' type is not supported on HMI. Request was not displayed`
3. SDL responds with `UNSUPPORTED_RESOURCE` resultCode and `success=true` to mobile application

**Observed behavior**
HMI responds with `WARNINGS` result code to SDL.

**OS & Version Information**
OS: Ubuntu 18.04
SDL: release/7.0.0 54246454
HMI: develop 931877c 

**Logs**
[hmi_log_warning.log](https://github.com/smartdevicelink/sdl_hmi/files/5459937/hmi_log_warning.log)

**Comment by GetmanetsIrina** [comment]
@theresalech Please note, this is a regression issue found by Luxoft during 7.0 release manual testing.

**Comment by theresalech** [comment]
@GetmanetsIrina please advise when Luxoft has a PR submitted to resolve the issue. However, as we are planning to release SDL 5.4 on November 5, 2020, we cannot guarantee that this PR will be included in the release.

**Comment by AKalinich-Luxoft** [comment]
@theresalech please notice PR with fix has been submitted and ready for Livio review

**Comment by jacobkeeler** [comment]
Fixed with #450 (although Core behavior does not exactly match the description for Alert because of https://github.com/smartdevicelink/sdl_core/issues/1597)
