### ISSUE TITLE
HMI aborts AlertManeuver, PerformInteraction requests with STATIC images

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#443]
**Precondition:**
1. SDL and HMI are started
2. Mobile app is registered and activated
3. CreateInteractionChoiceSet is added with STATIC image as precondition for PerformInteraction

**Reproduction Steps:**
1. Request AlertManeuver/PerformInteraction RPC with `STATIC` image

**Expected behavior:**
1. HMI processes the request but no not show the icon
2. HMI responds with `UNSUPPORTED_RESOURCE` resultCode + the message of the kind `Image of '%' type is not supported on HMI. Request was not displayed`
3. SDL responds with `UNSUPPORTED_RESOURCE` resultCode and success=true to mobile app (also with choiceId in case of PerformInteraction request)

**Observed behavior:**
1. HMI does not process the request
2. HMI responds with `WARNINGS` resultCode to AlertManeuver and `UNSUPPORTED_RESOURCE` resultCode to PerformInteraction  + the message of the kind `Image of '%' type is not supported on HMI. Request was not processed`
![image](https://user-images.githubusercontent.com/11210973/97676143-dc66ae00-1a98-11eb-83ce-ccb4d203d519.png)

**OS & Version Information**
OS: Ubuntu 18.04
SDL: release/7.0.0 54246454
HMI: develop 931877c

**Comment by GetmanetsIrina** [comment]
@theresalech Please note, this is a regression issue found by Luxoft during 7.0 release manual testing.

**Comment by theresalech** [comment]
@GetmanetsIrina please advise when Luxoft has a PR submitted to resolve the issue. However, as we are planning to release SDL 5.4 on November 5, 2020, we cannot guarantee that this PR will be included in the release.

**Comment by AKalinich-Luxoft** [comment]
@theresalech please notice PR with fix has been submitted and ready for Livio review

**Comment by jacobkeeler** [comment]
Fixed with #450 (although Core behavior does not exactly match the description because of https://github.com/smartdevicelink/sdl_core/issues/1596)
