### ISSUE TITLE
HMI sends 2 responses to one request ScrollableMessage and SetGlobalProperties in case the request contains not existed image

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#444]
**Bug Report**
HMI sends 2 responses to one request `UI.ScrollableMessage` and `UI.SetGlobalProperties` in case the request contains not existed image

**Reproduction Steps**
1. Start SDL, HMI, connect Mobile, register new App
2. The <missed_icon.png> does NOT exists at app sub-directory of "AppStorageFolder" (the value defined at .ini file)
3. Mobile app requests ScrollableMessage/SetGlobalProperties with the image that is absent on file system

**Expected Behavior**
1. SDL->HMI:  “UI.ScrollableMessage/SetGlobalProperties" `{ ...<parameter_name> = { value ="missed_icon.png",imageType ="DYNAMIC" }..}`
2. The request is displayed without an icon on HMI.
3. HMI -> SDL: result":{"code":21,"method":"UI.ScrollableMessage/SetGlobalProperties", info: Requested image(s) not found}}
4. SDL -> MOB: ScrollableMessage/SetGlobalProperties (“resultCode”:”WARNINGS”, '’success”:true, info: Requested image(s) not found.

**Observed Behavior**
1.HMI responds 2 times with SUCCESS resultCode and with WARNINGS resultCode 
2. SetGlobalPropeties response is sent to the mobile app with SUCCESS resultCode
3. HMI sends WARNINGS resultCode to ScrollableMessage request, but not close ScrollableMessage pop-up and sends second response with SUCCESS resultCode to SDL after timeout is expired
 
**OS & Version Information**
OS: Ubuntu 18.04
SDL: https://github.com/smartdevicelink/sdl_core/commits/release/7.0.0 (54246454776513b68161258b46299b48e4352f3f)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (931877cb68e56522d9f6db1d6c5751decf6c988e)
Mobile app: 20201007

**Logs:**
[hmi_2_responses.log](https://github.com/smartdevicelink/sdl_hmi/files/5464336/hmi_2_responses.log)

**Comment by GetmanetsIrina** [comment]
@theresalech Please note, this is a regression issue found by Luxoft during 7.0 release manual testing.

**Comment by theresalech** [comment]
@GetmanetsIrina please advise when Luxoft has a PR submitted to resolve the issue. However, as we are planning to release SDL 5.4 on November 5, 2020, we cannot guarantee that this PR will be included in the release.

**Comment by AKalinich-Luxoft** [comment]
@theresalech please notice PR with fix has been submitted and ready for Livio review

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/451
