### ISSUE TITLE
HMI responds with SUCCESS result code instead of WARNINGS in case PerformInteraction is requested with not existed image in choiceSet

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#445]
**Bug Report**
HMI responds with `SUCCESS` result code instead of `WARNINGS` in case PerformInteraction is requested with a not existed image in choiceSet

**Reproduction Steps**
1. Start SDL, HMI, connect Mobile, register new App
2. The <missed_icon.png> does NOT exists at app sub-directory of "AppStorageFolder" (the value defined at .ini file)
3. Mobile app adds CreateInteractionChoiceSet with the image that is absent on file system
4. Mobile app requests PerformInteraction with added ChoiceSet
5. User makes the choice on UI.PerformInteraction pop-up

**Expected Behavior**
HMI responds with WARNINGS result code and picked choiceId

**Observed Behavior**
HMI responds with SUCCESS resultCode
 
**OS & Version Information**
OS: Ubuntu 18.04
SDL: https://github.com/smartdevicelink/sdl_core/commits/release/7.0.0 (80973f45a1f137502521b24c26317e6391c08011)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (95d16aac6b39b5b6e3c020031925d25963f12eca)
Mobile app: 20201007

**Logs:**
[hmi_PI_SUCCESS_not_existed_image.log](https://github.com/smartdevicelink/sdl_hmi/files/5464605/hmi_PI_SUCCESS_not_existed_image.log)

**Comment by GetmanetsIrina** [comment]
@theresalech Please note, this is a regression issue found by Luxoft during 7.0 release manual testing.

**Comment by theresalech** [comment]
@GetmanetsIrina please advise when Luxoft has a PR submitted to resolve the issue. However, as we are planning to release SDL 5.4 on November 5, 2020, we cannot guarantee that this PR will be included in the release.

**Comment by AKalinich-Luxoft** [comment]
@theresalech please notice PR with fix has been submitted and ready for Livio review

**Comment by jacobkeeler** [comment]
Fixed via #450
