### ISSUE TITLE
HMI sends invalid OnAppPermissionConsent notification with appId=0

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#446]
**Bug Report**
HMI sends invalid `OnAppPermissionConsent` notification with appId=0

**Reproduction Steps**
1. Start SDL, HMI, connect Mobile, register new App
2. There are no specific permissions for the app
3. Go to HMI settings -> App permissions -> <app_name> -> button Back (permission list is empty)

**Expected Behavior**
HMI does not send invalid `OnAppPermissionConsent` notification

**Observed Behavior**
HMI sends
`{"jsonrpc":"2.0","method":"SDL.OnAppPermissionConsent","params":{"source":"GUI","consentedFunctions":[],"appID":0}}`
 
**OS & Version Information**
OS: Ubuntu 18.04
SDL: https://github.com/smartdevicelink/sdl_core/commits/release/7.0.0 (80973f45a1f137502521b24c26317e6391c08011)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (95d16aac6b39b5b6e3c020031925d25963f12eca)
Mobile app: 20201007

**Comment by GetmanetsIrina** [comment]
@theresalech Please note, this is a regression issue found by Luxoft during 7.0 release manual testing.

**Comment by theresalech** [comment]
@GetmanetsIrina please advise when Luxoft has a PR submitted to resolve the issue. However, as we are planning to release SDL 5.4 on November 5, 2020, we cannot guarantee that this PR will be included in the release.

**Comment by AKalinich-Luxoft** [comment]
@theresalech please notice PR with fix has been submitted and ready for Livio review

**Comment by dboltovskyi** [comment]
Closed via #453
