### ISSUE TITLE
HMI does not perform predefined actions by clicking the custom KEEP_CONTEXT softButton  on AlertManeuver pop-up

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#448]
**Bug Report**
HMI does not perform predefined actions by clicking the custom KEEP_CONTEXT softButton  on AlertManeuver pop-up

**Reproduction Steps**

1. Start SDL and HMI
2.  AlertManeuver is allowed by policies
3. Mobile app is registered and activated
4 .App requests AlertManeuver with softButtons
5 .Request is processed successfully by SDL and is resent to HMI
6. Press custom button

**Expected Behavior**

1. HMI shows AlertManeuver pop-up only with custom softButtons.
2. According to pressed button type HMI should perform the next actions:
DEFAULT_ACTION - Default action occurs. Standard behavior (e.g. SoftButton clears overlay)
STEAL_FOCUS - The calling app's dialog or related event should clear and the app should be brought into HMI_FULL
KEEP_CONTEXT - Current system context is maintained. An overlay is persisted even though a SoftButton has been pressed and the notification sent

**Observed Behavior**

1. AlertManeuver pop-up is shown with custom and **system defined "Close" SoftButtons.**
2. HMI does not perform predefined actions by pressing system defined "KEEP_CONTEXT" SoftButton

**OS & Version Information**

HMI: [1b49961](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
SDL: [80973f4](https://github.com/smartdevicelink/sdl_core/commits/release/7.0.0)

**Logs:**
[Alert.zip](https://github.com/smartdevicelink/sdl_hmi/files/5473716/Alert.zip)

**Comment by AKalinich-Luxoft** [comment]
@theresalech please notice PR with fix has been submitted and ready for Livio review

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/452
