### ISSUE TITLE
HMI sends OnUpdateFile and OnUpdateSubMenu notifications on Activate App

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#455]
**Bug Report**
HMI sends OnUpdateFile and OnUpdateSubMenu notification on Activate App to SDL

**Precondition:**
1. SDL and HMI are started
2. Mobile device connected
3. Mobile app is registered and activated
4. SubMenu item is added with an image that does exist on file system
AddSubMenu( "menuIcon":\{ "value":"missing_file.png", "imageType" = "DYNAMIC"}, "menuName":"Submenu Name 1", "menuID":1 }
5. App is deactivated
On HMI -> Options -> Exit "USER_EXIT"
App hmiLevel is "NONE"
or (On HMI -> press button "Home" )
App hmiLevel is "LIMITED"

**Reproduction Steps:**
1) Activate App
HMI→SDL: SDL.ActivateApp("appID":ID)

**Observed Behavior:**
HMI sends OnUpdateSubMenu and OnUpdateFile notifications
HMI→SDL: UI.OnUpdateFile":{"appID":ID,"fileName":"File_reference_name/missing_file.png"}}
HMI→SDL: UI.OnUpdateSubMenu ({"appID":ID,"menuID":1,"updateSubCells":true}}
SDL→APP: OnUpdateSubMenu ({"menuID":1,"updateSubCells":true}}
SDL→APP: OnUpdateFile":{"fileName":"missing_file.png"}}

**Expected Behavior:**
HMI does not send OnUpdateSubMenu and OnUpdateFile notifications

**OS & Version Information**
HMI: https://github.com/LuxoftSDL/sdl_hmi/tree/develop(f712d4e)
SDL: https://github.com/LuxoftSDL/sdl_core/tree/develop(a36ea82)

**Comment by VjKlepikov** [comment]
@theresalech Please note, this is a regression issue found by Luxoft during 7.0 release manual testing.

**Comment by AKalinich-Luxoft** [comment]
@theresalech please notice PR with fix is ready for Livio review

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/460
