### ISSUE TITLE
PNG image on POI is not shown as a template image

### ISSUE THREAD

**Issue by AKalinich-Luxoft** [smartdevicelink/sdl_hmi#457]
**Bug Report**
PNG image on POI is not shown as a template image

**Preconditions:**
1. SendLocation group is added to app policies
2. Start WebHMI and SDL
3. Register mobile application
4. Activate the application
5. SendLocation with .png image(isTemplate=true) is requested
6. Go to Navigation Tab on HMI

**Reproduction Steps:**
Change Display mode on HMI
 
**Expected behavior:**
HMI shows added POI in the POI list. The image is shown as a template for the current Display mode.

**Observed behavior:**
PNG image on POI is not shown as a template image

**OS & Version Information**
OS: Ubuntu 18.04
SDL: https://github.com/smartdevicelink/sdl_core/commits/release/7.0.0 (80973f45a1f137502521b24c26317e6391c08011)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (95d16aa)
Mobile app: 20201007

**Comment by AKalinich-Luxoft** [comment]
@theresalech Please note, this is a regression issue found by Luxoft during 7.0 release manual testing.

**Comment by AKalinich-Luxoft** [comment]
@theresalech please notice PR with fix has been submitted and ready for Livio review

**Comment by jacobkeeler** [comment]
Closed via #454
