### ISSUE TITLE
HMI does not apply Display mode to the Options menu and main app screen

### ISSUE THREAD

**Issue by AKalinich-Luxoft** [smartdevicelink/sdl_hmi#458]
**Bug Report**
HMI does not apply Display mode to the Options menu

**Preconditions:**
1. Start WebHMI and SDL
2. Register mobile application
3. Activate the application
4. Show with image(isTemplate=true) is requested
5. Stay on main app screen/ Go to app options

**Reproduction Steps:**
1. Change Display mode on HMI

**Expected behavior:**
HMI applies updated Display mode to the image on main app screen/Options menu

**Observed behavior:**
HMI does not apply Display mode to the image on main app screen/Options menu.

**OS & Version Information**
OS: Ubuntu 18.04
SDL: https://github.com/smartdevicelink/sdl_core/commits/release/7.0.0 (`80973f45a1f137502521b24c26317e6391c08011`)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (`95d16aa`)
Mobile app: 20201007

**Comment by AKalinich-Luxoft** [comment]
@theresalech Please note, this is a regression issue found by Luxoft during 7.0 release manual testing.

**Comment by AKalinich-Luxoft** [comment]
@theresalech please notice PR with fix has been submitted and ready for Livio review

**Comment by jacobkeeler** [comment]
Closed via #454
