### ISSUE TITLE
HMI sends OnButtonEvent, OnButtonPress notifications on VR command

### ISSUE THREAD

**Issue by AKalinich-Luxoft** [smartdevicelink/sdl_hmi#459]
**Description:**
HMI sends OnButtonEvent, OnButtonPress notifications on VR command 
Note: Issue is reproduced for all VR commands

**Occurrence:** 
50%

**Preconditions:** 
1. SDL and HMI are started. 
2. App is registered and activated
3. AddCommand with vrCommand is added `AddCommand( { "cmdID":1, "vrCommands":[sdl tester] } )`

**Steps to reproduce:**
1. Click on `VRButton` button (Button for VR commands emulation)
2. Select VR command "sdl tester"

**Actual result:**
HMI sends` VR.OnCommand:{"cmdID":1,"grammarID":ID,"appID":ID}`
`Buttons.OnButtonEvent","params":{"name":"PRESET_5","mode":"BUTTONUP"}}`
`Buttons.OnButtonPress","params":{"name":"PRESET_5","mode":"SHORT"}}`

**Expected result:**
HMI sends `VR.OnCommand:{"cmdID":1,"grammarID":ID,"appID":ID}`

**Environment:**
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (`7637690`)
SDL: https://github.com/smartdevicelink/sdl_core/releases/tag/7.0.0-RC2 (`80973f4`)
Mobile App: SPT 20201023

**Comment by AKalinich-Luxoft** [comment]
@theresalech Please note, this is NOT a regression issue found by Luxoft during 7.0 release manual testing.

**Comment by AKalinich-Luxoft** [comment]
@theresalech please notice PR with fix has been submitted and ready for Livio review

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/456
