### ISSUE TITLE
HMI sends UI.Alert response earlier than TTS.Alert during processing two Alert requests

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#465]
**Description:**
HMI sends UI.Alert response earlier than TTS.Alert during processing two Alert requests
Note:  Issue is applicable for Alert and SubtleAlert RPCs

**Occurrence:**  100%

**Preconditions:** 
1.   Start WebHMI and SDL
2.   Connect mobile device and consent it
3.   Register app from mobile device
4.   Activate the app

**Steps to reproduce:**
1. Send SubtleAlert request from the app
2. Send another SubtleAlert request from the app during the duration of displaying of SubtleAlert RPC from the previous step

**Expected result:**
HMI responds with code 4 to requests related to the second SubtleAlert request,
HMI send response to UI part only after sending response to TTS part
HMI -> SDL: {"error":{"code":4,"message":"TTS in progress. Rejected.","data":{"method":"TTS.Speak"}}}
HMI -> SDL: {"error":{"code":4,"message":"another SubtleAlert is active","data":{"method":"UI.SubtleAlert"}}}

Observed behavior:
HMI sends UI.Alert response earlier than TTS.Alert during processing two Alert requests
HMI -> SDL: {"error":{"code":4,"message":"another SubtleAlert is active","data":{"method":"UI.SubtleAlert"}}}
HMI -> SDL: {"error":{"code":4,"message":"TTS in progress. Rejected.","data":{"method":"TTS.Speak"}}}

**Environment:**
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (3bbcd28)
SDL: https://github.com/LuxoftSDL/sdl_core (7af6696)
Mobile App: SPT 20201023

**Comment by JackLivio** [comment]
Fixed by #464
