### ISSUE TITLE
`Uncaught ReferenceError: fileName is not defined` error on HMI during file deleting

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#503]
**Description:**
`Uncaught ReferenceError: fileName is not defined` error on HMI during file deleting

**Occurrence:** Sometimes (for specific file names)

**Preconditions:** 
1.   Start WebHMI and SDL
2.   Connect the mobile device
3.   Register app from the mobile device
4.   Activate the app

**Steps to reproduce:**
1. The mobile app requests PutFile with a filename like `IMG_20210309_172030.jpg`
2. The mobile app requests DeleteFile for added file

**Expected result:**
The file is removed successfully, there are no errors on HMI during `BasicCommunication.OnFileRemoved` processing

**Observed behavior:**
```
SDL -> HMI [17:33:16:239]: {"jsonrpc":"2.0","method":"BasicCommunication.OnPutFile","params":{"appID":972686529,"fileType":"GRAPHIC_JPEG","isSystemFile":false,"length":3469057,"offset":0,"persistentFile":false,"syncFileName":"/home/igetmanets/sdl/builds/DEVELOP/p/bin/storage/584421907_5cda5e51be15f78e846da1d60f5b5d3c88d4cbb4d9cce99475188460eec3ab95/IMG_20210309_172030.jpg"}}BasicCommunicationRPC.js:428 FFW.BasicCommunicationRPC.onRPCNotification
RPCClient.js:137 SDL -> HMI [17:33:23:861]: {"jsonrpc":"2.0","method":"BasicCommunication.OnFileRemoved","params":{"appID":972686529,"fileName":"/home/igetmanets/sdl/builds/DEVELOP/p/bin/storage/584421907_5cda5e51be15f78e846da1d60f5b5d3c88d4cbb4d9cce99475188460eec3ab95/IMG_20210309_172030.jpg","fileType":"GRAPHIC_JPEG"}}BasicCommunicationRPC.js:428 FFW.BasicCommunicationRPC.onRPCNotification
Model.js:218 Uncaught ReferenceError: fileName is not defined
    at d.onFileRemoved (Model.js:218)
    at d.onRPCNotification (BasicCommunicationRPC.js:455)
    at d [as onRPCNotification] (ember-1.0.pre.min.js:14)
    at d.onWSMessage (RPCClient.js:173)
    at WebSocket.socket.onmessage (RPCClient.js:81)
onFileRemoved @ Model.js:218
onRPCNotification @ BasicCommunicationRPC.js:455
d @ ember-1.0.pre.min.js:14
onWSMessage @ RPCClient.js:173
socket.onmessage @ RPCClient.js:81
```

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (fcd0b38)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (ad2dc80)
SPT: 20210305-Android (1076)

**Comment by GetmanetsIrina** [comment]
@jordynmackool, Please notice this is a regression issue

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/510
