### ISSUE TITLE
HMI shows the empty selection in the resolution drop-down list in case of selection the last element in the list

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#504]
**Description:**
HMI shows the empty selection in the resolution drop-down list in case of selection the last element in the list

**Occurrence:** 10/10

**Preconditions:** 
1.   Start WebHMI and SDL
2.   Connect the mobile device
3.   Register navigation app from the mobile device
4.   Activate the app

**Steps to reproduce:**
1. Select the last item in the drop-down list with the resolutions

**Expected result:**
The selected item is shown as selected

**Observed behavior:**
 HMI shows the empty selection in the drop-down list
![image](https://user-images.githubusercontent.com/11210973/110600706-e73ef700-818c-11eb-9338-ae2240b45776.png)

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (d8cd806)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (6e69663)
SPT: 20210217-Android (1074)

**Comment by GetmanetsIrina** [comment]
@Ypostolov is working on it

**Comment by Ypostolov** [comment]
@jordynmackool PR with fix is ready for Livio review.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/513
