### ISSUE TITLE
HMI shows resolutions in the drop-down list not corresponded to app settings in case of multiple apps

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#505]
**Description:**
HMI shows resolutions in the drop-down list not corresponded to app settings in case of multiple apps

**Occurrence:** 10/10

**Preconditions:** 
1. HMI and SDL are started
2. Navi app1 is registered and activated
3. Navi app1 is subscribed to video streaming updates via `GetSystemCapability` RPC
4. Navi app1 has provided supported video capabilities via `BC.OnAppCapabilityUpdated`
5. The drop-down list with resolutions is updated according to values received in `BC.OnAppCapabilityUpdated` for app1

**Steps to reproduce:**
1. Navi app2 is registered and activated (`BC.OnAppCapabilityUpdated` for app2 is not received yet)

**Expected behavior:**
 HMI shows the resolutions from capabilities(default set) in the drop-down list for newly registered app2

**Observed behavior:**
HMI shows an updated resolutions list in the drop-down list according to `BC.OnAppCapabilityUpdated` notification for all apps.

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (d8cd806)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (6e69663)
SPT: 20210217-Android (1074)

**Comment by Ypostolov** [comment]
@jordynmackool PR with fix is ready for Livio review.

**Comment by jordynmackool** [comment]
Thanks, @Ypostolov! Please advise if this is a regression issue for the 7.1.0 Release?

**Comment by jacobkeeler** [comment]
Closing with the merge fo #537
