### ISSUE TITLE
HMI sends redundant UI.OnKeyboardInput in case of `maskInputCharacters` setting

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#506]
**Description:** HMI sends redundant `UI.OnKeyboardInput` in case of `maskInputCharacters` setting

**Precondition:**
1. `OnKeyboardInputOnlyGroup` is assigned to mobile app
2. SDL and HMI are started
3. App is registered and activated

**Steps to reproduce:**
1. Send `SetGlobalProperties("maskInputCharacters":"ENABLE_INPUT_KEY_MASK")`

**Expected behavior:**
1. HMI sends `UI.OnKeyboardInput{"event":"INPUT_KEY_MASK_ENABLED"}` after receiving `UI.SetGlobalProperties` request
2. HMI responds to `UI.SetGlobalProperties` request

**Observed behavior:**
HMI sends redundant `UI.OnKeyboardInput` notification in case of `maskInputCharacters` setting
```
RPCClient.js:137 SDL -> HMI [11:14:10:806]: {"id":37,"jsonrpc":"2.0","method":"UI.SetGlobalProperties","params":{"appID":1487557736,"keyboardProperties":{"keypressMode":"RESEND_CURRENT_ENTRY","maskInputCharacters":"ENABLE_INPUT_KEY_MASK"}}}
UIRPC.js:157 FFW.UI.onRPCRequest
KeyboardController.js:222 Masking keyboard input characters
UIRPC.js:2118 FFW.UI.OnKeyboardInput
RPCClient.js:323 HMI -> SDL [11:14:10:819]: {"jsonrpc":"2.0","method":"UI.OnKeyboardInput","params":{"event":"INPUT_KEY_MASK_ENABLED"}}
UIRPC.js:2118 FFW.UI.OnKeyboardInput
RPCClient.js:323 HMI -> SDL [11:14:10:823]: {"jsonrpc":"2.0","method":"UI.OnKeyboardInput","params":{"event":"INPUT_KEY_MASK_ENABLED"}}
UIRPC.js:1786 FFW.UI.UI.SetGlobalPropertiesResponse
RPCClient.js:323 HMI -> SDL [11:14:10:830]: {"jsonrpc":"2.0","id":37,"result":{"code":0,"method":"UI.SetGlobalProperties"}}
RPCClient.js:137
```
**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (17a9e62)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (6e69663)
SPT: 20210217-Android (1074)

**Comment by JackLivio** [comment]
@GetmanetsIrina Is the SetGlobalProperties request sent when the keyboard is not present as described by the test?

**Comment by JackLivio** [comment]
This might highlight another issue. Im not sure this OnKeyboardInput event should even be sent by the hmi if theres no keyboard being displayed.

**Comment by JackLivio** [comment]
I thought  `UI.OnKeyboardInput{"event":"INPUT_KEY_MASK_ENABLED"}` only applied for when the user toggled between the two hide/show modes if they were given the option.

**Comment by GetmanetsIrina** [comment]
> Is the SetGlobalProperties request scenario sent when the keyboard is not presented?

It's doesn't matter, because in the current implementation HMI sends `UI.OnKeyboardInput` notification despite the keyboard is presented or not.

> This might highlight another issue. Im not sure this OnKeyboardInput event should even be sent by the hmi if theres no keyboard being displayed.

I agree ... Makes sense.

> I thought UI.OnKeyboardInput{"event":"INPUT_KEY_MASK_ENABLED"} only applied for when the user toggled between the two hide/show modes if they were given the option.

At first, it was made in such a way. But it was decided to update logic to the current state during the Ford review if I'm not mistaken.
