### ISSUE TITLE
HMI sends deprecated OnFindApplications notification to SDL

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#509]
**Preconditions:**
SDL and HMI are started

**Reproduction Steps:**
Select the "Apps" menu on HMI/ Register mobile app

**Expected Behavior:**
HMI does not send deprecated OnFindApplications notification to SDL

**Observed Behavior:**
`HMI→SDL: BasicCommunication.OnFindApplications`

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (fcd0b38)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (ad2dc80) 
SPT: 20210305-Android (1076)

**Comment by Ypostolov** [comment]
@jordynmackool  PR with fix is ready for Livio review.
