### ISSUE TITLE
HMI responds with SUCCESS resultCode instead of WARNINGS to AddCommand with `SecondaryImage` in case isTemplate=true and image type is not .png

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#514]
**Description:**
HMI responds with `SUCCESS` resultCode instead of `WARNINGS` to `AddCommand` request with `SecondaryImage` in case `isTemplate=true` and image type is not .png

**Occurrence:** 10/10

**Preconditions:**
1. SDL and HMI are started
2. The mobile app is registered and activated
3. <name>.jpg image is added successfully using `PutFile` RPC

**Steps to reproduce:**
1. Mobile app requests `AddCommand("SecondaryImage" ={ "value": <name>.jpg, "isTemplate" = true, "imageType" = "DYNAMIC" }, ... )`

**Expected behavior:**
HMI receives `UI.AddCommand("SecondaryImage" = { "value": <name>.jpg, "isTemplate" = true, "imageType" = "DYNAMIC" })` request and responds with `WARNINGS` result code

**Observed behavior:**
HMI responds with `SUCCESS` result code to `UI.AddCommand` request with the image not supported as a template 
```
SDL -> HMI [16:41:7:825]: {"id":256,"jsonrpc":"2.0","method":"UI.AddCommand","params":{"appID":2015757036,"cmdID":2,"menuParams":{"menuName":"Item to Add 2","parentID":0,"position":0,"secondaryText":"Secondary text","tertiaryText":"Tertiary Text"},"secondaryImage":{"imageType":"DYNAMIC","isTemplate":true,"value":"/home/igetmanets/sdl/builds/DEVELOP/p/bin/storage/584421907_71546855d6279ef70d20909b292c42c2dcb02cd06bde01485da52d13e304ebf4/IMG_20210309_172030.jpg"}}}

UIRPC.js:157 FFW.UI.onRPCRequest
UIRPC.js:1790 FFW.UI.UI.AddCommandResponse
RPCClient.js:323 HMI -> SDL [16:41:7:833]: {"jsonrpc":"2.0","id":256,"result":{"code":0,"method":"UI.AddCommand"}}
```

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (c9fc559)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (41c804d)
SPT: SPT: 20210305-Android (1076)

**Comment by GetmanetsIrina** [comment]
@jordynmackool, Please notice this issue is related to feature [`Main Menu UI Updates`](https://github.com/smartdevicelink/sdl_core/issues/3195) that should be released in the 7.1 release.

**Comment by Ypostolov** [comment]
Luxoft is working on it.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/544
