### ISSUE TITLE
HMI does not apply Display mode to the main Alert image

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#516]
**Description:**
HMI does not apply display mode to the main `Alert` image

**Preconditions:**
1. SDL and HMI are started
2. Mobile app is registered and activated

**Steps to reproduce:**
1. Mobile app requests `Alert( "AlertIcon" = { "value" = <image>.png, "imageType" = "DYNAMIC", "isTemplate" = true })`
2. Change Display mode

**Expected behavior:**
HMI applies display mode to the main `Alert` image

**Observed behavior:**
HMI does not apply display mode to the main `Alert` image
![image-2021-03-17-15-16-30-003](https://user-images.githubusercontent.com/11210973/111490059-601cf080-8743-11eb-886b-68142b856f3f.png)

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (c9fc559)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (41c804d)
SPT: SPT: 20210305-Android (1076)

**Comment by Ypostolov** [comment]
Luxoft is working on this issue.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/568
