### ISSUE TITLE
HMI does not set default "PLAY_PAUSE" playback indicator in case App request SetMediaClockTimer without audioStreamingIndicator parameter 

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#517]
HMI does not set default "PLAY_PAUSE" playback indicator in case App request SetMediaClockTimer without audioStreamingIndicator parameter 

**Precondition:**
    1. SDL and HMI are started
    2. App with HMI type 'Media' is registered
    3. App is activated
    4. App sends SetMediaClockTimer RPC with:
      "updateMode":"COUNTUP",
      "startTime": { "hours":0, "minutes":15, "seconds":30 },
      "audioStreamingIndicator":"PAUSE"
    5. The seek indicators are "PAUSE" for App
    'PLAY_PAUSE' button with "ico_pause.png" image is observed on HMI

**Steps to reproduce:**
1. Send SetMediaClockTimer RPC without audioStreamingIndicator:
"updateMode":"COUNTUP",
"startTime": { "hours":0, "minutes":15, "seconds":30 }

**Expected result:**
1. HMI sets default "PLAY_PAUSE" playback indicator
'PLAY_PAUSE' button with "ico_play_pause.png" image is observed on HMI

**Actual result:**

1. HMI does not set default "PLAY_PAUSE" playback indicator
'PLAY_PAUSE' button with "ico_pause.png" image is observed on HMI
![Image](https://user-images.githubusercontent.com/45170482/111502881-ee4aa400-874e-11eb-8244-c7697cd14131.png)

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (fed2ae4)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (ad2dc80)
SPT: 20210305-Android (1076)

**Comment by VjKlepikov** [comment]
@jordynmackool, Please notice this issue is related to feature [Media Skip Indicators](https://github.com/smartdevicelink/sdl_core/issues/2625) that should be released in the 7.1 release.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/572
