### ISSUE TITLE
HMI does not send AddSubMenu response with settable resultCode "WARNINGS"

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#520]
**Description:**
HMI does not send AddSubMenu response with settable resultCode "WARNINGS"

**Note:** Defect is applicable:
1. For success type of response (resultCode):
    WARNINGS
    WRONG_LANGUAGE
    RETRY
    SAVED
2. For RPC's:
    AddSubMenu
    SetGlobalProperties

**Precondition:**
    1. Start SDL and HMI.
    2. Connect mobile device via any transport.
    3. Mobile application is registered and activated.

**Steps to reproduce:**
    1. On HMI go to "Setting -> RPC Control -> App name ->  AddSubMenu
    2. Set resultCode "WARNINGS"  from the drop-down list and click "Back" button
    3. Send AddSubMenu (params)

**Expected result:**
HMI responds with success type of response ( WARNINGS resultCode) to UI.AddSubMenu requests from SDL
     SDL→HMI: UI.AddSubMenu ( params )
     HMI→SDL: {"code":21,"method":"UI.AddCommand"}

**Actual result:**
HMI responds with ( SUCCESS resultCode )  to UI.AddSubMenu requests from SDL
     SDL→HMI: UI.AddSubMenu ( params )
     HMI→SDL: {"code":0,"method":"UI.AddCommand"}

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop ( c9fc559)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (41c804d)
SPT: 20210305-Android (1076)

**Comment by VjKlepikov** [comment]
@jordynmackool, Please notice this is a regression issue

**Comment by Ypostolov** [comment]
Luxoft is working on it.

**Comment by jordynmackool** [comment]
@Ypostolov please advise when the fix for this PR will be ready for Livio review?

**Comment by Ypostolov** [comment]
@jordynmackool Fix for this issue is currently in progress and will be ready for Livio review till the end of this week.

**Comment by Ypostolov** [comment]
@jordynmackool PR with fix is ready for Livio review. Thank you.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/551
