### ISSUE TITLE
HMI is unable to send "RC.SetGlobalProperties response with error resultCode

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#521]
**Description:**
HMI is unable to send "RC.SetGlobalProperties response with error resultCode

**Precondition:**
    1. Start SDL and HMI.
    2. Connect mobile device via any transport.
    3. Mobile application is registered and activated.

**Steps to reproduce:**
     1. On HMI go to "Setting -> RPC Control -> App name ->  RC.SetGlobalProperties
     Set resultCode (ex. "GENERIC_ERROR" ) from the drop-down list and click "Back" button
     2. Send RC.SetGlobalProperties(params)

**Expected result:**
HMI responds with an erroneous type of response ( ERROR resultCode ( ex. GENERIC_ERROR))
     SDL→HMI: RC.SetGlobalProperties ( params )
     HMI→SDL: { "code":22,"method":" RC.SetGlobalProperties" }

**Actual result:**
HMI is unable to send "RC.SetGlobalProperties response with error resultCode

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (c9fc559)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (41c804d)
SPT: 20210305-Android (1076)

**Comment by ShobhitAd** [comment]
Closed via #545
