### ISSUE TITLE
HMI displays part of "tertiary text" is outside of the menu item

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#522]
**Description:**
HMI displays part of "tertiary text" is outside of the menu item

**Precondition:**
 1. HMI and SDL are started
 2. Mobile app("Enable Auto Send RPC" is disabled) is registered
 3. App is activated

**Steps to reproduce:**
Mobile app requests AddSubMenu RPC with `tertiaryText` parameter and all mandatory parameters
1. App -> SDL:  AddSubMenu({ "menuID" = <value>, "menuName" = <value>, "tertiaryText" = <value> })
2. SDL -> HMI: UI.AddSubMenu({ "menuID" = <value>, "menuName" = <value>, "tertiaryText" = <value> })
3. HMI→SDL: UI.AddSubMenu({ "code"= 0 })
4. SDL→App: AddSubMenu({ "success" = true, "resultCode" = SUCCESS })

**Expected result:**
HMI shows added submenu with `tertiaryText` value on the right side of the submenu

**Actual result:**
HMI displays part of "tertiary text" is outside of the menu item
![Image](https://user-images.githubusercontent.com/45170482/111621782-0e32a400-87f1-11eb-8286-a2f71caab58e.png)

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop ( c9fc559)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (7fad546)
SPT: 20210305-Android (1076)

**Comment by VjKlepikov** [comment]
@jordynmackool, Please notice this issue is related to feature [`Main Menu UI Updates`](https://github.com/smartdevicelink/sdl_core/issues/3195) that should be released in the 7.1 release.

**Comment by Ypostolov** [comment]
Luxoft is working on it.

**Comment by VjKlepikov** [comment]
@jordynmackool @JackLivio This is regression issue that was introduced by fix for [ ‘HMI displays part of "tertiary text" is outside of the menu item’](https://github.com/smartdevicelink/sdl_hmi/issues/522) Please advise if Livio team plans to submit a fix for this reported issue?

**Comment by jordynmackool** [comment]
@VjKlepikov Livio will work on submitting a PR for this reported issue. Thanks!

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/533
