### ISSUE TITLE
HMI unable to connect to Policy Manager after Ignition cycle (EXTERNAL_PROPRIETARY)

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_hmi#527]
**Description:**
HMI unable to connect to Policy Manager after Ignition cycle (EXTERNAL_PROPRIETARY)
Occurrences: 90%

**Precondition:**
1. Make sure SDL is built in `EXTERNAL_PROPRIETARY` policy mode
2. SDL is started (using `start.sh` script which runs python Policy Manager)
3. HMI is started (`External Policies` option is switched on)
4. New apps is registered

**Steps to reproduce:**
1. Activate app and consent device.
=> SDL starts PTU and sends SDL.OnStatusUpdate(UPDATE_NEEDED, UPDATING)
2. Send Ignition Off
3. Start SDL (using `start.sh` script)
=> SDL and Policy Manager are restarted

**Expected result:**
- HMI re-connects to Policy Manager
- Policy Manager is able to handle `BC.OnSystemRequest`

**Actual result:**
- HMI tries to connect to Policy Manager to early
- Policy Manager unable to handle `BC.OnSystemRequest`

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (0df6608)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (7fad546)
SPT: 20210305-Android (1076)

**Comment by AKalinich-Luxoft** [comment]
@jordynmackool PR with fix is ready for Livio review.

**Comment by jacobkeeler** [comment]
Fixed with the merge of #540
