### ISSUE TITLE
HMI sends OnKeyboardInput notification with incorrect 'INPUT_KEY_MASK_DISABLED' event

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#528]
**Description:**
HMI sends OnKeyboardInput notification with incorrect 'INPUT_KEY_MASK_DISABLED' event in case SetGlobalProperties request with 'USER_CHOICE_INPUT_KEY_MASK' 

**Precondition:**
 1. Default app_policies groups is updated in sdl_preloaded_pt.json
 "app_policies": {
            "default": { ...
                "groups": [
                    "Base-4", "OnKeyboardInputOnlyGroup"
                ], 
... }}
2. SDL and HMI are started
3. Apps is registered and activated

**Steps to reproduce:**
Send SetGlobalProperties RPC with (maskInputCharacters: *"USER_CHOICE_INPUT_KEY_MASK"*)

**Expected result:**
1. HMI sends UI.OnKeyboardInput\{"event":"*INPUT_KEY_MASK_ENABLED*"} after receiving UI.SetGlobalProperties request
2. HMI responds to UI.SetGlobalProperties request

**Actual result:**
HMI sends UI.OnKeyboardInput\{"event":"*INPUT_KEY_MASK_DISABLED*"} after receiving UI.SetGlobalProperties request

SDL -> HMI [15:5:31:169]: {"id":31,"jsonrpc":"2.0","method":"UI.SetGlobalProperties","params":{"appID":1890327978,"keyboardProperties":{"keypressMode":"RESEND_CURRENT_ENTRY","maskInputCharacters":"USER_CHOICE_INPUT_KEY_MASK"}}}
RPCClient.js:323 HMI -> SDL [15:5:31:180]: {"jsonrpc":"2.0","method":"UI.OnKeyboardInput","params":{"event":"INPUT_KEY_MASK_DISABLED"}}
UIRPC.js:1790 FFW.UI.UI.SetGlobalPropertiesResponse
RPCClient.js:323 HMI -> SDL [15:5:31:187]: {"jsonrpc":"2.0","id":31,"result":{"code":0,"method":"UI.SetGlobalProperties"}}

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (0df6608)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (7fad546)
SPT: 20210305-Android (1076)

**Comment by VjKlepikov** [comment]
@jordynmackool, Please notice this issue is related to feature [`Keyboard Enhancements`](https://github.com/smartdevicelink/sdl_core/issues/2970) that should be released in the 7.1 release.

**Comment by VjKlepikov** [comment]
@jordynmackool @JackLivio This is regression issue that was introduced by fix for [‘Fix/redunant keyboard mask notification’](https://github.com/smartdevicelink/sdl_hmi/pull/511) Please advise if Livio team plans to submit a fix for this reported issue?

**Comment by jordynmackool** [comment]
@VjKlepikov Livio will work on submitting a PR for this reported issue. Thanks!
