### ISSUE TITLE
HMI sends redundant UI.OnKeyboardInput 'INPUT_KEY_MASK_ENABLED' on press 'KEYBOARD' button

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#529]
**Description:**
HMI sends redundant UI.OnKeyboardInput 'INPUT_KEY_MASK_ENABLED' on press 'KEYBOARD' button

**Precondition:**
 1. Default app_policies groups is updated in sdl_preloaded_pt.json
 "app_policies": {
            "default": { ...
                "groups": [
                    "Base-4", "OnKeyboardInputOnlyGroup"
                ], 
... }}
2. SDL and HMI are started
3. Apps is registered and activated
4. App sends SetGlobalProperties RPC with (maskInputCharacters: "USER_CHOICE_INPUT_KEY_MASK")

**Steps to reproduce:**
1. Press "KEYBOARD" button on HMI

**Expected result:**
1.  HMI *does not* send OnKeyboardInput notification

**Actual result:**
1.  HMI sends UI.OnKeyboardInput\{"event":"*INPUT_KEY_MASK_ENABLED*"} after receiving UI.SetGlobalProperties request

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (0df6608)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (7fad546)
SPT: 20210305-Android (1076)

**Comment by VjKlepikov** [comment]
@jordynmackool, Please notice this issue is related to feature [`Keyboard Enhancements`](https://github.com/smartdevicelink/sdl_core/issues/2970) that should be released in the 7.1 release.

**Comment by VjKlepikov** [comment]
@JackLivio Please note that the issue is reproduced on 5.5.0 [Release](https://github.com/smartdevicelink/sdl_hmi/tree/release/5.5.0)  in case:

Precondition: the same

Steps to reproduce:
1. Press 'unmask' key on HMI keyboard.
2. Press "KEYBOARD" button on HMI

Expected result:
1. HMI→SDL: "UI.OnKeyboardInput": ({{"event":"INPUT_KEY_MASK_DISABLED"}}})
SDL→App: "OnKeyboardInput": ({{"event":"INPUT_KEY_MASK_DISABLED"}}})
2. HMI does not send OnKeyboardInput notification

Actual result:
1. HMI→SDL:  "UI.OnKeyboardInput": ({{"event":"INPUT_KEY_MASK_DISABLED"}}})
SDL→App: "OnKeyboardInput": ({{"event":"INPUT_KEY_MASK_DISABLED"}}})

2. HMI sends UI.OnKeyboardInput
{"event":"*INPUT_KEY_MASK_ENABLED*"}
after receiving UI.SetGlobalProperties request

Environment:
SDL: https://github.com/smartdevicelink/sdl_core/tree/7.1.0-RC1
HMI: https://github.com/smartdevicelink/sdl_hmi/commits/release/5.5.0 (b1d31f8)
SPT: SPT: 20210305-Android (1076)

**Comment by JackLivio** [comment]
@VjKlepikov I dont believe this is an issue. When the mask mode is USER_CHOICE_INPUT_KEY_MASK, every time the keyboard is presented it will by default have masking enabled.
