### ISSUE TITLE
HMI sets limitedCharacterList for common Keyboard on the main HMI screen

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#530]
**Description:**
HMI sets limitedCharacterList for common Keyboard on the main HMI screen

**Precondition:**
 1. SDL and HMI are started
 2. App is registered and activated
 3. SetGlobalProperties is requested with *"limitedCharacterList"*: [ "1", "a" ]

**Steps to reproduce:**
 1. Go to apps list
 Open the common Keyboard from the main HMI screen

**Expected result:**
1. All characters are enabled on the keyboard.
2. HMI does not set limitedCharacterList for common Keyboard on the main HMI screen

**Actual result:**
1. All omitted characters are greyed out (disabled) except for ["1", "a"] on the keyboard.

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (0df6608)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (7fad546)
SPT: 20210305-Android (1076)

**Comment by jacobkeeler** [comment]
Fixed with the merge of #574
