### ISSUE TITLE
HMI applies the same display layout for Media and Non-media in case of layout setting via SetDisplayLayout

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#535]
**Description:**
HMI applies the same display layout for Media and Non-media in case of layout setting via SetDisplayLayout

**Precondition:**
1. SDL and HMI are started
2.  Media mobile app is registered and activated

**Steps to reproduce:**
1. Mobile app requests SetDisplayLayout(displayLayout = non-media)

**Expected result:**
HMI applies non-media template

**Actual result:**
HMI does not update the layout

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/7.1.0-RC1
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (7fad546)
SPT: SPT: 20210305-Android (1076)

**Comment by jacobkeeler** [comment]
Closing with the merge of #566
