### ISSUE TITLE
HMI AlertManeuver pop-up is shown in case Navi.AlertManeuver request contains only appID

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#536]
**Description:**
HMI AlertManeuver pop-up is shown in case Navi.AlertManeuver request contains only appID

**Precondition:**
1. SDL and HMI are started
2.  Media mobile app is registered and activated

**Steps to reproduce:**
1. Mobile app requests AlertManeuver RPC without softButtons

**Expected result:**
HMI does not show AlertManeuver pop-up, shows only TTS.Speak related to AlertManeuver request

**Actual result:**
HMI shows the empty AlertManeuver pop-up

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/7.1.0-RC1
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (7fad546)
SPT: SPT: 20210305-Android (1076)

**Comment by jacobkeeler** [comment]
I created a PR to make the layout look a little clearer in this case, see #565

**Comment by jacobkeeler** [comment]
Closing with the merge of #565
