### ISSUE TITLE
HMI does not send DeleteCommand response to SDL in case delete the top level submenu

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#569]
**Description:**
HMI does not send DeleteCommand response to SDL in case delete the top level submenu

**Precondition:**
    1. SDL and HMI are started
    2. Mobile device connected
    3. Mobile app is registered and activated
    4. SubMenu item is added
    AddSubMenu("menuID":1, "menuName":"Submenu Name 1")
    5. Nested submenu item are added (each submenu is nested in the previous submenu)
    Send AddSubMenu(parentID=1, "menuID":2, "menuName":"Submenu Name 2")
    Send AddSubMenu(parentID=2, "menuID":3, "menuName":"Submenu Name 3")
    Send AddSubMenu(parentID=3, "menuID":4, "menuName":"Submenu Name 4")
    6. AddCommand item is added to nested SubMenu
    Send AddCommand("menuParams: { "parentID:4, "menuName":"Item to Add 1", "position":0)

**Steps to reproduce:**
1. Delete submenu item (item is menu-tree branch)
    Send DeleteSubMenu("menuID":4)

**Expected result:**
DeleteCommand requests for the requested submenu and all contents under that submenu

APP→SDL: DeleteSubMenu ( "menuID":4 )
SDL→HMI: UI.DeleteSubMenu ( params, "menuID":4)
HMI→SDL: UI.DeleteSubMenu ( resultCode = SUCCESS )
SDL→HMI: UI.DeleteCommand ( "appID":ID, "cmdID":ID )
HMI→SDL: UI.DeleteCommand ( resultCode = SUCCESS )
SDL→APP: DeleteSubMenu ( "resultCode":"SUCCESS", "success":true )
Submenu is successfully removed
"Submenu Name 4" button is not displayed on HMI

**Actual result:**
APP→SDL: DeleteSubMenu ( "menuID":4 )
SDL→HMI: UI.DeleteSubMenu ( params, "menuID":4)
HMI→SDL: UI.DeleteSubMenu ( resultCode = SUCCESS )
SDL→HMI: UI.DeleteCommand ( "appID":ID, "cmdID":ID )

**HMI does not send response UI.DeleteCommand: 
 HMI→SDL: UI.DeleteCommand ( resultCode = SUCCESS )**

SDL→APP: DeleteSubMenu ( "resultCode":"SUCCESS", "success":true )

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (fcd0b38033)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (6e69663)
SPT: 20210217-Android (1074)

**Comment by Ypostolov** [comment]
@jordynmackool PR with fix is ready for Livio review. Thank you.

**Comment by jacobkeeler** [comment]
Closing, Core issue (see https://github.com/smartdevicelink/sdl_core/issues/3747)
