### ISSUE TITLE
HMI shows navigation buttons for all registered apps in case one of these apps has an active subscription

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#578]
**Description:**
HMI shows navigation buttons for all registered apps in case one of these apps has an active subscription

**Precondition:**
    1. SDL and HMI are started
    2. Mobile device connected
    3. Navigation app1 and navigation app2
    4. Mobile app1 is activated

**Steps to reproduce:**
1. Mobile app requests SubscribeButton for of navigation buttons (e.g. NAV_ZOOM_IN, NAV_ZOOM_OUT)
2. Go to `Nav Buttons` on app1 HMI screen
3. Go to `Nav Buttons` on app2 HMI screen

**Expected result:**
HMI shows buttons with an active subscription for app1 in `Nav Buttons` menu and does not show these buttons for app2 that has no active subscription for these buttons

**Actual result:**
HMI shows buttons for app1 and app2 in `Nav Buttons` menu

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (eaec9b4)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (c50b0a7)
SPT: SyncProxyTester (20210407)

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/591
