### ISSUE TITLE
HMI sends OnInteriorVehicleData notification without default moduleId

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#582]
**Description:**
HMI sends OnInteriorVehicleData notification without default 'moduleId'

**Precondition:**
1. SDL and HMI are started

**Steps to reproduce:**
1. On HMI go to -> "SETTING" -> "SEAT"
2. Update "heatingEnabled" on HMI and press 'Set' button

**Expected result:**
1. Default  ID "d38e4a05-b17c-28e3-9d38-e4a05b17c28e" is observed on HMI
2. HMI sends OnInteriorVehicleData notification with 'moduleId':"d38e4a05-b17c-28e3-9d38-e4a05b17c28e"

**Actual result:**
1. Default ID "d38e4a05-b17c-28e3-9d38-e4a05b17c28e" is observed on HMI
2. HMI sends OnInteriorVehicleData notification without 'moduleId'
 
**Occurrences:** 10/10

**Environment**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (8e9640d)
SPT:  20210305-Android (1076)

**Comment by Ypostolov** [comment]
@jordynmackool PR with fix is ready for Livio review. Thank you.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/585
