### ISSUE TITLE
HMI does not update capabilities based on template

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_hmi#586]
When switching templates while an app is subscribed to `DISPLAYS` system capabilities, the HMI should send an `OnSystemCapabilityUpdated` message with the new template's capabilities, but instead it sends a static set of capabilities from `Abstract/data.js` (which also currently have incorrect `buttonCapabilities`, since they include RC buttons).

Reproduction Steps:

1. App is registered with `MEDIA` and `NAVIGATION` app HMI types
2. App sends `GetSystemCapability(DISPLAYS)` with `subscribe=true`
3. App sends `Show` request with `templateConfiguration`, `templateName="NON-MEDIA"`

Expected behavior:

App receives `SUCCESS` response to `Show` request
App receives `OnSystemCapabilityUpdated(DISPLAYS)` with the display capabilities for the `NON-MEDIA` template

Actual behavior:

App receives `SUCCESS` response to `Show` request
App receives `OnSystemCapabilityUpdated(DISPLAYS)` with a set of display capabilities which does not correspond to any template.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/590
