### ISSUE TITLE
HMI does not update the timeout for timeoutPrompt during timeout resetting

### ISSUE THREAD

**Issue by yshatskyi** [smartdevicelink/sdl_hmi#599]
### Bug Report
HMI does not update the timeout for timeoutPrompt during timeout resetting

##### Precondition
1. SDL and HMI are started
2. Mobile app is registered and activated
3. CreateInteractionChoiceSet is added

##### Reproduction Steps
1. Mobile app requests PerformInteraction with interactionMode = "MANUAL_ONLY" and timeoutPrompt, timeout = 10000
2. Press Reset timeout for UI.PerformInteraction

##### Expected Behavior
HMI shows timeoutPrompt before the timeout expiration (before about 2-3 sec)

##### Observed Behavior
HMI shows timeoutPrompt according to timeout received in UI.PI request

##### Browser & Version Information
* Browser and Version: Chromium (Version 91.0.4472.101)
* SDL HMI Version: develop (d2c882a8b1a872ab99c2c8f70c6f31140624f258)
* Testing Against: sdl_core (develop, 35f5a0684a36a2a965d5f0e9e784687fa7d82914), SyncProxyTester (20210305-Android)

**Comment by yshatskyi** [comment]
Luxoft team is going to prepare the fix

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/606
