### ISSUE TITLE
WebHMI "Reset timeout" window countdown counter is out of UI viewport

### ISSUE THREAD

**Issue by yshatskyi** [smartdevicelink/sdl_hmi#600]
### Bug Report
WebHMI "Reset timeout" window has countdown counter which should be visible to user; however only left part of its label is visible, at least in maximized Chromium window on 1080p display

##### Precondition
1. In sdl_preloaded_pt.json default app_policies groups contain group with "SetInteriorVehicleData" RPC, "moduleType" contains some remote control module, e. g.:
```
        "app_policies": {
            "default": {
                "groups": [
                    "RemoteControl"
                ],
                "moduleType": [ "CLIMATE" ]
            },
```
2. SDL and HMI are started.
3. App1 and app2 are registered and activated with "REMOTE_CONTROL" type.
4. In HMI settings, [gears icon] -> Policies -> RSDL Functionality Options -> set Allowed, Ask driver

##### Reproduction Steps
1. In 1st app, execute SetInteriorVehicleData for some allowed RC module (e. g. moduleType: CLIMATE, skip ModuleId to use 1st module of the type)
2. In 2nd app, execute SetInteriorVehicleData for same allowed RC module

##### Expected Behavior
"Reset timeout" windows is displayed with all elements fully visible

##### Observed Behavior
Countdown counter is out of UI viewport (see right edge)

##### Browser & Version Information
* Browser and Version: Chromium (Version 91.0.4472.101)
* SDL HMI Version: develop (d2c882a8b1a872ab99c2c8f70c6f31140624f258)
* Testing Against: sdl_core (develop, 35f5a0684a36a2a965d5f0e9e784687fa7d82914), SyncProxyTester (20210305-Android)

**Comment by yshatskyi** [comment]
Luxoft team is going to prepare the fix

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/601
