### ISSUE TITLE
Error `isEmptyObject is not a function` durin SEAT data update

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#602]
### Bug Report
Error `isEmptyObject is not a function` durin SEAT data update

##### Precondition
1. `SEAT` module and `RemoteControl` group are assigned to the app in the sdl_preloaded_pt.json
```
"groups": [
     "Base-4", "RemoteControl"
],
"moduleType": [ "SEAT"]
```
2. HMI and SDL are started

##### Reproduction Steps
1. on HMI go to Settings(gear icon)->Seat(on the left panel)
2. Update some data on the Seat view
3. Press button Set on the top

##### Expected Behavior
HMI applies the update and sends this update in the RC.OnInteriorVehicleData notification
note: verification should be performed with and without mobile app

##### Observed Behavior
```
SeatModel.js:331 Uncaught TypeError: this.isEmptyObject is not a function
    at d.applySettings (SeatModel.js:331)
    at d.action (RCModulesController.js:763)
    at d.triggerAction (ember-1.0.pre.min.js:15)
    at d.actionUp (Button.js:142)
    at d.trigger (ember-1.0.pre.min.js:16)
    at d [as trigger] (ember-1.0.pre.min.js:14)
    at d.handleEvent (ember-1.0.pre.min.js:16)
    at d.invokeForState (ember-1.0.pre.min.js:16)
    at d.handleEvent (ember-1.0.pre.min.js:16)
    at ember-1.0.pre.min.js:16
applySettings @ SeatModel.js:331
action @ RCModulesController.js:763
triggerAction @ ember-1.0.pre.min.js:15
actionUp @ Button.js:142
trigger @ ember-1.0.pre.min.js:16
d @ ember-1.0.pre.min.js:14
handleEvent @ ember-1.0.pre.min.js:16
invokeForState @ ember-1.0.pre.min.js:16
handleEvent @ ember-1.0.pre.min.js:16
(anonymous) @ ember-1.0.pre.min.js:16
c @ ember-1.0.pre.min.js:14
Ember.run @ ember-1.0.pre.min.js:14
_bubbleEvent @ ember-1.0.pre.min.js:16
(anonymous) @ ember-1.0.pre.min.js:16
dispatch @ jquery-1.7.2.min.js:3
i @ jquery-1.7.2.min.js:3
```

##### Browser & Version Information
* Browser and Version: Chromium (Version 92.0.4515.159)
* SDL HMI Version: develop (d2c882a8b1a872ab99c2c8f70c6f31140624f258)
* Testing Against: sdl_core (develop, 35f5a0684a36a2a965d5f0e9e784687fa7d82914), SyncProxyTester (20210305-Android)

**Comment by GetmanetsIrina** [comment]
Please note Luxoft team is going to prepare the fix

**Comment by iCollin** [comment]
Thank you, closed via https://github.com/smartdevicelink/sdl_hmi/pull/604
