### ISSUE TITLE
GetInteriorVehicleDataConsent pop-up for resetting timeout is not closed by response sending

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#611]
#### Description:
GetInteriorVehicleDataConsent pop-up for resetting timeout is not closed by response sending

#### Precondition:
1. RemoteControl group is assigned to the app
2. Some RC module is assigned to the app
3. HMI and SDL are started
4. Access mode is set to `Ask Driver`(Settings->RSDL Functionality Options->Access mode)
5. 2 RC apps are registered

#### Steps to reproduce:
1. The first app requests SetInteriorVehicleData(CLIMATE) and allocates the module for app
2. The second app requests SetInteriorVehicleData(CLIMATE)
3. Press OK/Close button on GetInteriorVehicleDataConsent pop-up

#### Expected result:
HMI sends the response for RC.GetInteriorVehicleDataConsent RPC and closes the pop-up for timeout resetting

#### Actual result:
HMI does not close the pop-up for GetInteriorVehicleDataConsent by response sending

 ##### Browser & Version Information
* Browser and Version: Chromium (Version 92.0.4515.159)
* SDL HMI Version: release/5.6.0 (ceb8b3c)
* Testing Against: SDL: release/8.0.0 (5da5770), SyncProxyTester(Version 20210729-Android (1082))

**Comment by GetmanetsIrina** [comment]
Please notice Luxoft team is going to prepare a fix.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/614
