### ISSUE TITLE
HMI does not reject Navi.AlertManeuver request in case another AlertManeuver request is in progress

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#619]
#### Description:
HMI does not reject `Navi.AlertManeuver` request in case another `AlertManeuver` request is in progress

#### Precondition:
1. `"Navigation-1"` group is assigned to the app
2. HMI and SDL are started
3. A mobile app is registered and activated

#### Steps to reproduce:
1. Mobile app request `AlertManeuver`
2. Mobile app requests the same `AlertManeuver RPC` when the first one is in progress

#### Expected result:
HMI rejects `TTS.Speak` and `Navi.AlertManeuver` requests that are related to the second request with result code 4. HMI continues the timers counting and showing of pop-ups for the first request without interruption. HMI sends responses for the first request when the timers are expired.

#### Actual result:
HMI does not reject the second `Navi.AlertManeuver` request shows an additional `Navi.AlertManeuver` request on `OnResetTimeout` pop-up and sends `Navi.AlertManeuver` response with invalid id=0 after timeout is expired.
![image](https://user-images.githubusercontent.com/11210973/134321791-fa92204f-03f5-4ac8-b60f-e6c407e8addc.png)

```
SDL -> HMI [12:21:13:391]: {"id":352,"jsonrpc":"2.0","method":"Navigation.AlertManeuver","params":{"appID":289949524}}

NavigationRPC.js:176 FFW.Navigation.onRPCRequest
RPCClient.js:137 SDL -> HMI [12:21:13:463]: {"id":353,"jsonrpc":"2.0","method":"TTS.Speak","params":{"appID":289949524,"speakType":"ALERT_MANEUVER","ttsChunks":[{"text":"Text to Speak","type":"TEXT"}]}}

TTSRPC.js:143 FFW.TTS.onRPCRequest
TTSRPC.js:456 FFW.TTS.Started
RPCClient.js:323 HMI -> SDL [12:21:13:469]: {"jsonrpc":"2.0","method":"TTS.Started"}
RPCClient.js:137 SDL -> HMI [12:21:15:570]: {"id":354,"jsonrpc":"2.0","method":"Navigation.AlertManeuver","params":{"appID":289949524}}

NavigationRPC.js:176 FFW.Navigation.onRPCRequest
RPCClient.js:137 SDL -> HMI [12:21:15:578]: {"id":355,"jsonrpc":"2.0","method":"TTS.Speak","params":{"appID":289949524,"speakType":"ALERT_MANEUVER","ttsChunks":[{"text":"Text to Speak","type":"TEXT"}]}}

TTSRPC.js:143 FFW.TTS.onRPCRequest
TTSRPC.js:355 FFW.TTS.SpeakResponse
RPCClient.js:323 HMI -> SDL [12:21:15:580]: {"jsonrpc":"2.0","id":355,"error":{"code":4,"message":"TTS in progress. Rejected.","data":{"method":"TTS.Speak"}}}
TTSRPC.js:416 FFW.TTS.TTS.SpeakResponse
RPCClient.js:323 HMI -> SDL [12:21:23:580]: {"jsonrpc":"2.0","id":353,"result":{"code":0,"method":"TTS.Speak"}}
TTSRPC.js:467 FFW.TTS.Stopped
RPCClient.js:323 HMI -> SDL [12:21:23:592]: {"jsonrpc":"2.0","method":"TTS.Stopped"}
NavigationRPC.js:468 FFW.Navigation.Navigation.AlertManeuverResponse
RPCClient.js:323 HMI -> SDL [12:21:23:595]: {"jsonrpc":"2.0","id":354,"result":{"code":0,"method":"Navigation.AlertManeuver"}}
NavigationRPC.js:468 FFW.Navigation.Navigation.AlertManeuverResponse
RPCClient.js:323 HMI -> SDL [12:21:25:579]: {"jsonrpc":"2.0","id":0,"result":{"code":0,"method":"Navigation.AlertManeuver"}}
```

##### Browser & Version Information
* Browser and Version: Chromium (Version 92.0.4515.159)
* SDL HMI Version: release/5.6.0 (63316f2) 
* Testing Against: SDL: release/8.0.0 (de58a410) , SyncProxyTester(Version 20210729-Android (1082))

**Comment by GetmanetsIrina** [comment]
Please notice Luxoft team is going to prepare a fix.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/620
