### ISSUE TITLE
VR pop-up overlaps the pop-up for timeout resetting during VR.PerfromInteraction

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#622]
#### Description:
VR pop-up overlaps the pop-up for timeout resetting during VR.PerfromInteraction

#### Precondition:
1. SDL and HMI are started
2. Mobile app is registered and activated
3. CreateInteractionChoiceSet is added

#### Steps to reproduce:
1. Mobile app requests PerformInteraction(BOTH)/PerfromInteraction(VR)

#### Expected result:
Opened pop-ups do not overlap each other

#### Actual result:
![image](https://user-images.githubusercontent.com/11210973/134468755-5b80c21c-f2b3-4cb5-a0cc-f06d975c66fb.png)

##### Browser & Version Information
* Browser and Version: Chromium (Version 92.0.4515.159)
* SDL HMI Version: release/5.6.0 (63316f2) 
* Testing Against: SDL: release/8.0.0 (de58a410) , SyncProxyTester(Version 20210729-Android (1082))

**Comment by GetmanetsIrina** [comment]
Please notice Luxoft team is going to prepare a fix.

**Comment by iCollin** [comment]
@GetmanetsIrina are you sure this issue is more important than https://github.com/smartdevicelink/sdl_hmi/issues/600?

**Comment by GetmanetsIrina** [comment]
@iCollin , this issue is not more important, on the PR https://github.com/smartdevicelink/sdl_hmi/pull/623 we checked both cases and they are working as expected.

**Comment by iCollin** [comment]
Thank you! Closed via https://github.com/smartdevicelink/sdl_hmi/pull/623
