### ISSUE TITLE
Does not hide the "OK"/PLAY_PAUSE button after successful unsubscription

### ISSUE THREAD

**Issue by VNikiforov-dev** [smartdevicelink/sdl_hmi#628]
**Description:**

HMI does not hide the "PLAY_PAUSE" (OK) button after successful unsubscription

**Precondition:**

1. SDL and HMI are started
2. Media mobile app is registered and activated

**Steps to reproduce:**

1. App requests UnsubscribeButton("PLAY_PAUSE")

**Expected result:**

HMI responds with
`{"success":true,"resultCode":"SUCCESS"}`
HMI hides the "PLAY_PAUSE" button after successful unsubscription

**Actual result:**

HMI **does not hide** the "OK" button after successful unsubscription

**OS & Version Information**

- OS/Version: [Ubuntu 18]
- SDL Core Version: [ https://github.com/smartdevicelink/sdl_core/tree/release/8.0.0 (5da5770 )]
- HMI: [https://github.com/smartdevicelink/sdl_hmi/tree/release/5.6.0 (9812a79)]
- SPT: 20210729-Android

**Comment by VNikiforov-dev** [comment]
Please notice Luxoft team is going to prepare a fix.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/641
