### ISSUE TITLE
HMI is crashed after switching app during PHONE_CALL

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#648]
##### Preconditions:
 1. SDL and HMI are started
 2. App1 with HMI type 'Media', media:false is registered and activated
 3. App2 with HMI type 'Media', media:true is registered
 4. App2 is activated (App1 in LIMITED status, App2 in FULL status)
 ##### Steps to reproduce:
 1. Click to "incoming call!"
```
HMI->SDL: OnEventChanged(PHONE_CALL, isActive=true)
SDL->App2: OnHMIStatus(FULL, NOT_AUDIBLE)
```
App1 is LIMITED and NOT_AUDIBLE

2. Activate app1
```
SDL->App2: OnHMIStatus(LIMITED, NOT_AUDIBLE)
SDL->App1: OnHMIStatus(FULL, NOT_AUDIBLE)
```
3. Wait for phone call ends (15-20 sec after start call)
```
HMI->SDL: OnEventChanged(PHONE_CALL, isActive=false)
SDL->App2: OnHMIStatus (LIMITED, AUDIBLE)
```
App1 stay in FULL level and NOT_AUDIBLE
##### Expected result:
 1. App2 is LIMITED, AUDIBLE
 App1 is FULL, NOT_AUDIBLE 

##### Actual result:
 1. App2 is LIMITED, AUDIBLE
 App1 is FULL, NOT_AUDIBLE

But HMI open App2 (pic1) and crashed (pic2)
*NOTE:* crash reproduced after problem with display -> click "home" 
[HMI.log](https://github.com/smartdevicelink/sdl_hmi/files/7569067/HMI.log)
[SmartDeviceLinkCore_phone_call.log](https://github.com/smartdevicelink/sdl_hmi/files/7569068/SmartDeviceLinkCore_phone_call.log)

![image](https://user-images.githubusercontent.com/11210973/142595748-22d097b8-d6e3-43f1-bc85-3349ef2989cf.png)
![image](https://user-images.githubusercontent.com/11210973/142595767-af14c91b-5b48-4a81-97ca-fd7083cd196e.png)

##### OS & Version Information:
* OS/Version: [Ubuntu 18.04]
* SDL Core Version:  https://github.com/LuxoftSDL/sdl_core/tree/develop (35f5a06)
* HMI: https://github.com/LuxoftSDL/sdl_hmi/tree/develop (d2c882a)
* SPT: 20210325-Android

**Comment by GetmanetsIrina** [comment]
Please notice Luxoft team is going to prepare a fix.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/651
