### ISSUE TITLE
HMI does not apply Display mode to the VR list

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#649]
##### Precondition:
1. SDL and HMI are started
2. Mobile app is registered and activated
##### Steps to reproduce:
1. Open VR menu
2. Change Display Mode to "Day mode"
##### Expected result:
HMI applies Display mode to the VR list (first and next page)
##### Actual result:
HMI does not apply Display mode to the VR list (first page)
![image](https://user-images.githubusercontent.com/11210973/142601340-bf25b292-cac5-418f-9d23-0cb0e1248f73.png)

![image](https://user-images.githubusercontent.com/11210973/142601431-a7c5801e-6adf-4562-b87b-c44cd2942d0c.png)
##### OS & Version Information:
* OS/Version: [Ubuntu 18.04]
* SDL Core Version:  https://github.com/smartdevicelink/sdl_core/commits/release/8.0.0 (de58a41)
* HMI: https://github.com/LuxoftSDL/sdl_hmi/tree/release/5.6.0 (18b9826)
* SPT: 20210729-Android

**Comment by GetmanetsIrina** [comment]
Please notice Luxoft team is going to prepare a fix.

**Comment by jacobkeeler** [comment]
Closed via #652
