### ISSUE TITLE
HMI doesn't stop play audio when PHONE_CALL event happend

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#654]
#### Preconditions:
1. SDL and HMI are started
2. Executed from HMI folder

./deploy_server.sh

3. Mobile app is registered:
(with syncMsgVersion = { majorVersion = 8, minorVersion = 0 } or greater)
App with HMI type 'NAVIGATION' and checkbox 'Media': true
4. App is activated
`OnHMIStatus:{ "audioStreamingState":"AUDIBLE", "hmiLevel":"FULL" }`
#### Steps to reproduce:
1. Start audio stream(app menu ->Stream Services -> Start Service (Unsecure should be checked) -> Select Audio Sample 2m 45 sec)
Note: SPT sends all audio data for the short time
2. Get Incoming call
Click "Incoming Call" on the HMI
`HMI->SDL: BasicCommunication.OnEventChanged: {"eventName":"PHONE_CALL","isActive":true}`

#### Expected result:
1. App goes to FULL(STREAMABLE, NOT_AUDIBLE) state
SDL->App:
`OnHMIStatus:{ "audioStreamingState":"NOT_AUDIBLE", "hmiLevel":"FULL" }`
2. HMI stops playing audio

#### Actual result:
1. App goes to FULL(STREAMABLE, NOT_AUDIBLE) state
SDL->App:
`OnHMIStatus:{ "audioStreamingState":"NOT_AUDIBLE", "hmiLevel":"FULL" }`
2. HMI is continuing play audio

#### OS & Version Information:

* OS/Version: [Ubuntu 18.04]
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (1e88e6f39 )
* HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (d5e648a)
* SPT: 20210729-Android

**Comment by GetmanetsIrina** [comment]
Please notice Luxoft team is going to prepare a fix.

**Comment by jacobkeeler** [comment]
Fixed via #655
