### ISSUE TITLE
HMI displays the value for TTS+VR application language over the section name

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#657]
#### Precondition:
1. HMI and SDL are started
2. Mobile app is registered and activated

#### Steps to reproduce:
1. Mobile app requests `ChangeRegistration` RPC with value for Language parameter

#### Expected result:
HMI displays the value below the section name

#### Actual result:
![image](https://user-images.githubusercontent.com/11210973/144605870-211a9914-c2c5-4b8a-b2e0-63a808b61c34.png)

#### OS & Version Information:
* OS/Version: [Ubuntu 18.04]
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (1e88e6f39 )
* HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (d5e648a)
* SPT: 20210729-Android

**Comment by GetmanetsIrina** [comment]
Please notice Luxoft team is going to prepare a fix.

**Comment by jacobkeeler** [comment]
Closed via #660
