### ISSUE TITLE
HMI does not apply Display mode to the main screen image

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#661]
#### Precondition:
1. SDL and HMI are started
2. Mobile app is registered and activated

#### Steps to reproduce:
1. App send “Show” :
- Activate: “Graphic”
- select: DYNAMIC
- select: <name>.png
- activate: “isTemplate”= ON
2. Change Display mode

#### Expected result:
HMI applies display mode to the main screen image

#### Actual result:
HMI does not apply Display mode to the main screen image
![image](https://user-images.githubusercontent.com/11210973/145044560-12fb1266-1837-4072-98c4-5dd92a6df390.png)

#### OS & Version Information:
* OS/Version: [Ubuntu 18.04]
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (1e88e6f39 )
* HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (d5e648a)
* SPT: 20210729-Android

**Comment by GetmanetsIrina** [comment]
Please notice Luxoft team is going to prepare a fix.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/662
