### ISSUE TITLE
HMI does not send videoStreaming parameter as part of UI.GetCapabilities response

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#669]
HMI does not send 'videoStreaming' parameter as part of UI.GetCapabilities response

**Occurrence:** always

**Precondition:**
SDL is started

**Steps to reproduce:**
Start WebHMI

**Observed behavior:**
HMI sends UI.GetCapabilities response which contains `hmiCapabilities` without videoStreaming parameter

  "hmiCapabilities":{
            "navigation":true,
            "phoneCall":true
        },

**Expected behavior:**
HMI sends UI.GetCapabilities response which contains `hmiCapabilities` with 'videoStreaming' parameter

  "hmiCapabilities":{
            "navigation":true,
            "phoneCall":true,
            "videoStreaming":true
        },

**Logs:**
[Logs.zip](https://github.com/smartdevicelink/sdl_hmi/files/8224232/Logs.zip)

**OS & Version Information:**

OS/Version: [Ubuntu 18]
SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/8.1.0 (15ddebb4)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/release/5.7.0 (2aa1bdf)
SPT: 20210729-Android

**Comment by VjKlepikov** [comment]
@theresalech PR with fix is ready for Livio review.
Please notice this is a non-regression issue. It's also reproduced on release 5.6.0 We propose to include this PR to release 5.7.0 according to https://github.com/smartdevicelink/sdl_hmi/issues/669#issuecomment-1064154986

**Comment by theresalech** [comment]
@VjKlepikov thanks for the information! We are currently preparing the Core 8.1 Release Candidate for Steering Committee review but will work to include the fix for this issue in SDL HMI 5.7 if time allows. Thank you!

**Comment by jacobkeeler** [comment]
Closed via #670
