### ISSUE TITLE
Cannot activate an app

### ISSUE THREAD

**Issue by yang1070** [smartdevicelink/sdl_hmi#8]
in the Html HMI, after clicking the app "syncproxytest", a popup showing "Activation in progress...", but the app does not get activated.

**Comment by JackLivio** [comment]
@yang1070 Do you have policies disabled in the smartDeviceLink.ini config file?

**Comment by JackLivio** [comment]
If that is the case, then it is a known issue that we are working on a fix for.

[](https://github.com/smartdevicelink/sdl_core/issues/842)

**Comment by yang1070** [comment]
yes, I have policy check disabled.

**Comment by yang1070** [comment]
not repro with latest code
