### ISSUE TITLE
What does this web HMI do?

### ISSUE THREAD

**Issue by grimlockrocks** [smartdevicelink/sdl_hmi#9]
Hello,

I am running SDL core on Ubuntu, and I have loaded the HTML page which shows the head unit mock-up. What exactly does this web HMI do? How do I know if this is connected with the running SDL core? And what I can do with this web HMI to demonstrate core functions? 

Thank you!!

**Comment by BrandonHe** [comment]
The web HMI can process RPC request from core, and give response accordingly. 

When you are running sdl core and hmi in Ubuntu, then you need an app that can be connected to SDL core, if this app is available, just connect your phone with Ubuntu via usb, then run the app in the phone side, it will show in hmi(by clicking italia "i", then find connected app under find new apps).

Maybe you can find more information [here](https://github.com/smartdevicelink/sdl_core/wiki/SmartDeviceLink) for how to

**Comment by gunnarx** [comment]
With my tests it only runs in Chrome browser, if this helps...
