### ISSUE TITLE
HMI shall not send a OnInteriorVehicleData notification if a parameter is included in the request but the value is the same as the current value

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_hmi#96]
HMI shall not send a OnInteriorVehicleData notification if a parameter is included in the request but the value is the same as the current value (i.e. no change).
(This issue is applicable to all types of modules)

Steps: 
1. mobile sends a valid SetInteriorVehicleData to HMI with some params that will be changed 
2. HMI apply that changes and send OnInteriorVehicleData notification with changed parameters
3. mobile sends a valid SetInteriorVehicleData to HMI **_with the same params_**

Expected:
HMI doesn't send OnInteriorVehicleData notification because the params values are the same as the current values

Observed:
HMI send OnInteriorVehicleData notification

**Comment by jacobkeeler** [comment]
Minor issue, just a redundant notification in some cases

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/593
